### ISSUE TITLE
Checkboxes only work in HTML

### ISSUE THREAD

**Issue by lise-henry** [kivikakk/comrak#108]
Currently, checkboxes lists are (as far as I understand) are lists where the `[ ]` and `[X]` are replaced by some HTML code. While this works for HTML outputs this prevents this features being used in other output (e.g. LaTeX in my use case), while most other features work really pretty nicely. Do you think it would be possible to modify the AST instead of the content of the list item? Since list items have a `NodeList` elements I suppose it would be possible to add some fields to distinguish between 'normal' list items and the two variants of checkboxes without breaking compatibility.

Anyway, thanks for the work :)

**Comment by kivikakk** [comment]
It should be possible indeed! Adding a new inline node would do the trick. I'm unfortunately short on time and unable to implement this myself, but would happily accept a PR to do so.

**Comment by lise-henry** [comment]
Ok, I'll try to look into it if I have some time
