### ISSUE TITLE
Inconsistent conversion of `A***B*C*`

### ISSUE THREAD

**Issue by mikeando** [kivikakk/comrak#111]
While fuzz testing my application, I found a case where I converting a markdown string to an AST, then write the AST back to markdown, 
then read the result back to an AST again, and the first and second ASTs do not match.

While I don't expect this to be perfectly reversible in all cases, this case seems especially odd:

The initial string is 

~~~
A***B*C*
~~~

which becomes the AST

~~~
<text value="A*"/>
<emph>
     <emph>
          <text value="B"/>
      </emph>
      <text value="C"/>
</emph>
~~~

which is then re-rendered as markdown as:

~~~
A\***B*C*
~~~

which is then parsed as the AST

~~~
<text value="A***B"/>
<emph>
    <text value="C"/>
</emph>
~~~

**Comment by kivikakk** [comment]
This is per upstream [`cmark`](https://github.com/commonmark/cmark):

```console
$ echo 'A***B*C*' | build/src/cmark -t xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text xml:space="preserve">A*</text>
    <emph>
      <emph>
        <text xml:space="preserve">B</text>
      </emph>
      <text xml:space="preserve">C</text>
    </emph>
  </paragraph>
</document>
$ echo 'A***B*C*' | build/src/cmark -t commonmark
A\***B*C*
$ echo 'A\***B*C*' | build/src/cmark -t xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text xml:space="preserve">A***B</text>
    <emph>
      <text xml:space="preserve">C</text>
    </emph>
  </paragraph>
</document>
$
```

We should get this fixed upstream, and then copy the changes into comrak. I've opened an upstream issue at https://github.com/commonmark/cmark/issues/292.
