### ISSUE TITLE
Feature Requests: Command line Flag to turn on all common extensions?

### ISSUE THREAD

**Issue by jrmiller82** [kivikakk/comrak#116]
Could we get a `-a` or `--all` to keep us from having to type `-e foo` over and over for each feature? Like a flag that turns on all extensions except for my header tags and soft links become hard links?

**Comment by kivikakk** [comment]
I think this is not a good idea. As more extensions are added, anyone using such a flag would have a surprising result when upgrading as the meaning of their documents changes.

I'm not sure what you mean by "my header tags and soft links become hard links", but if you already want to exclude extensions, that suggests maybe enabling all extensions at once isn't a good idea, and that we would also need to implement options to then disable already-enabled extensions. The complexity burden for a convenience option is undesirable.

If you find yourself typing out the list of extensions a lot, you might need to instead consider what your process is that leads to this, and whether or not you could reduce that burden another way.

**Comment by jrmiller82** [comment]
I didn't realize that the soft line breaks become hard line breaks weren't a `-e foo` extension but a separate flag. What about a CLI flag just for the github-style extensions? Like `--git` or something? I completely see what you're saying, but the git extensions haven't changed in a long time and likely won't, right?

**Comment by kivikakk** [comment]
That's a good point. I think the best design would be a `--gfm` flag that enables the GFM extensions, which is to say `strikethrough`, `tagfilter`, `table`, `autolink`, and `tasklist`. It should also enable `--github-pre-lang`.

I'm happy to do this, but would also like to offer writing the PR to you in case it's something you'd like to do.

**Comment by jrmiller82** [comment]
I can take a first stab at it. My rust-fu is still novice to intermediate.

**Comment by jrmiller82** [comment]
Should have you a PR tonight.

**Comment by jrmiller82** [comment]
PR #118 up. I hope it helps. I apologize for my first rambling feature request; I used incorrect vocabulary and I apologize for any wasted time. I hope the PR helps with UI/UX on the CLI. :)

**Comment by kivikakk** [comment]
Thank you so much, that's been merged! And nothing to apologise for, no time's wasted when communicating. :)

Let me know if you'd like a new release of comrak to be made with these new changes.

**Comment by jrmiller82** [comment]
You're welcome! I have no need for an immediate release if you'd like to wait until your regularly planned release schedule. :)

**Comment by kivikakk** [comment]
Haha, I ask in part because there's no regular cadence at present. I'm a real fan of this change so I'll make a release now!

**Comment by jrmiller82** [comment]
Thanks. I'll be using this as a lib in a future project I think so I'm sure if I come across something neat I'll bring it up here. Might even dig into the AST portion. Thanks for maintaining this lib. It's super snappy and clean.

**Comment by kivikakk** [comment]
Sounds great; thank you! I'm really glad it's been useful to you. (0.6.1 has been released, btw!)
