### ISSUE TITLE
Stop using timebomb

### ISSUE THREAD

**Issue by ignatenkobrain** [kivikakk/comrak#119]
I am packaging comrak for Fedora and I found that it uses very old crate `timebomb`. I would appreciate if you would switch to some more modern dependency.

For example, `wait-timeout`.

**Comment by kivikakk** [comment]
`wait-timeout` has a very different API and would require restructuring the code.

What's the actual concern with `timebomb`? It hasn't been updated in years but that's because it's so simple it doesn't need to change: https://docs.rs/timebomb/0.1.2/src/timebomb/lib.rs.html#22-46

**Comment by ignatenkobrain** [comment]
My particular problem was that in order to package timebomb for Fedora I would have to package something like 4 more crates which did not have releases for 3 years.

But if you think, those are good enough.. I can package them.

**Comment by kivikakk** [comment]
I'm not sure how packaging Rust crates on Fedora works, but is it possible to omit the dev dependencies in the resulting package? `timebomb` is only needed for a test and isn't listed as a primary dependency.

It's only a single test and I can rewrite it to omit the dependency entirely, if you can't skip the dev dependencies. Easier than you packaging the rest.

**Comment by ignatenkobrain** [comment]
We try to package even dev-dependencies and we run `cargo test` to ensure that tests are passing.

But it seems there are more things depending on it like `zmq`. So I will just package it.

**Comment by kivikakk** [comment]
@ignatenkobrain Thanks for opening an issue!
