### ISSUE TITLE
Syntax highlighting for code blocks

### ISSUE THREAD

**Issue by bschwind** [kivikakk/comrak#129]
Hi there, this is more of a question than an issue. I'm writing a simple static site generator which converts markdown to HTML. When encountering code blocks, I'd like to syntax highlight them. I'm currently using [syntect](https://github.com/trishume/syntect) for that, but the resulting HTML gets escaped by comrak, presumably by [this line](https://github.com/kivikakk/comrak/blob/8b9f255cd5fb9c3c8ced4117682ac1e828232bb7/src/html.rs#L494).

Before I read the code, I was expecting `unsafe_ = true` to allow this. Is this use case currently possible with comrak? Should `unsafe_ = true` disable HTML escaping?

Thanks for the great library!

**Comment by kivikakk** [comment]
Hey! This escaping site should remain as-is -- it's so that something like this:

````markdown
Here's my HTML example:

```html
<strong>Hello!</strong>
```
````

renders as expected with the HTML displayed in full, i.e. you should be able to drop arbitrary text between the ```` ``` ```` and have it displayed verbatim.

When I highlight syntax, I do it in the opposite order: convert Markdown to HTML, then parse the resulting HTML into a DOM, find `pre code` blocks and then syntax highlight the inner text of that node using the language in the `code`'s `class`. `html5ever` might be a starting point for this.

You could also do it without DOM parsing by using a regex like `/<pre><code class="language-([^"]+)">([^<]*)<\/code>/`, remembering to unescape the capture group for the code itself. It's a lot hackier than DOM parsing, but it's also probably faster and I think just as correct. The `htmlescape` crate will do the unescaping.

Let me know if any of this doesn't make sense!

**Comment by bschwind** [comment]
Thanks for the response, it makes perfect sense!

Totally understand the desire to keep text in the code fences verbatim. I think the easiest path forward for me is to just keep a personal fork that allows unescaped HTML. Syntect will escape HTML during highlighting so your HTML example actually works fine in my case. But I know comrak can't assume this will happen, so it's reasonable to keep it as-is.

**Comment by kivikakk** [comment]
You're right; if syntect will run on and escape every code block, then it works just as well. Good luck with your project!

**Comment by bschwind** [comment]
Appreciate the quick response, I wanted to make sure I was on the right track and wasn't missing any features of comrak :)

**Comment by norbertkeri** [comment]
For anyone else who might find this:

A beter way to do this might be to replace the fenced codeblocks with `HtmlBlock`, as those are not escaped. You will have to set `unsafe_: true` in your comrak options for this to work though.
