### ISSUE TITLE
How to allow benign html tags?

### ISSUE THREAD

**Issue by Boscop** [kivikakk/comrak#130]
How can I allow benign html tags such as these to survive the md2html conversion?
```html
<button>
[This is a link](http://www.google.com "Link to Google")
</button>
```

Or similar tags, such as those used in the default email template [here](http://cakedown.alexandredeschamps.ca/).

**Comment by kivikakk** [comment]
Two things are needed here:

1. You'll need to use `--unsafe` (or set `unsafe_ = true` in the `ComrakOptions` struct) to preserve raw HTML.
2. CommonMark needs you to separate the HTML tag from the Markdown link like this:

   ```markdown
   <button>

   [This is a link](http://www.google.com "Link to Google")

   </button>
   ```

   This will produce the following HTML:

   ```html
   <button>
   <p><a href="http://www.google.com" title="Link to Google">This is a link</a></p>
   </button>
   ```

   If you don't want the `<p>` tags wrapping, you'll need to just write out all the HTML.

Hope this helps!

**Comment by Boscop** [comment]
But how to only allow safe html tags? I don't want to allow all.
Does comrak differentiate, or do I need to use `ammonia` to sanitize?

**Comment by kivikakk** [comment]
You will need to use a third-party library and postprocess. `comrak` is only meant to fulfil the CommonMark/GFM spec; it does not contain a full HTML parser.

**Comment by Boscop** [comment]
Ok
