### ISSUE TITLE
Option to use triple-backticks for codeblocks

### ISSUE THREAD

**Issue by casey** [kivikakk/comrak#136]
I prefer triple-backticks for codeblocks, since i find it a little easier to edit. What would you think of an option to use triple-backticks for codeblocks, instead of indentation?

**Comment by kivikakk** [comment]
Do you mean like this?

`````markdown
Here's my code block:

```go
fn main() {
    println("hi")
}
```
`````

It's already supported, in base CommonMark; see <https://spec.commonmark.org/0.29/#fenced-code-blocks>.

**Comment by casey** [comment]
Ah, sorry, I should have been more precise, I was referring to an option to use backticks for codeblocks when dumping a parsed tree as CM, since parsing is already supported.

**Comment by kivikakk** [comment]
Aaaaah, yes. I think that's an excellent idea! You'll note the renderer already does this if there's an "info" string attached to the code block (for fenced code blocks like ````` ```ruby `````), so you could plug in the option at the same point to use the fenced style.

The `ComrakOptions` struct is getting crowded. Feel free to add it in, but also feel free to maybe decompose it a bit? (e.g. parse vs output options)

**Comment by kivikakk** [comment]
See #139 re: refactoring the options struct.
