### ISSUE TITLE
Bug parsing tasklists?

### ISSUE THREAD

**Issue by lunch-account** [kivikakk/comrak#142]
Have you given any thought on how to fix task lists (i.e. dot inclusion -> elision). Think this bug might occur because task lists are an extension, so you parse normally and then use regex for [ ].

**Comment by kivikakk** [comment]
Hi there! Could you clarify on "dot inclusion -> elision" or include an example case? I'm not quite sure what you mean. In general, though, there is often weirdness when it comes to extensions.

**Comment by lunch-account** [comment]
Sure. On github tasklists appear: 

- [ ] task

With Comrak this same code will render: 

- - [ ] task

**Comment by kivikakk** [comment]
Ah, I see! That's a matter of CSS styling — both GitHub and comrak output `<ul>` and `<li>`s for tasklists, but GitHub adds `.task-list-item` to task list `<li>`s and then use `list-style-type: none;` to not render the bullet.

You'll need to do HTML post-processing to add a class to `<li>`s that contain task list checkboxes and then CSS style accordingly, or we could consider adding support to the HTML outputter to add a (possibly configurable) class name in that case. I'm open to accepting a PR that does this.

**Comment by lunch-account** [comment]
This is great! HTML post-processing actually works well for my use case, so I am closing for now. Thank you!
