### ISSUE TITLE
Broken link callback gets passed normalised link labels

### ISSUE THREAD

**Issue by zacps** [kivikakk/comrak#143]
Given a link:

```markdown
[A link]
```

The callback will be given: `"a link"` and there is no way to determine the original text.

This is done here:

https://github.com/kivikakk/comrak/blob/660ec92260465d35e5b8f25062e36c09cb596744/src/parser/inlines.rs#L953

There should be an option to disable normalisation, or some other way to obtain the original link text.

**Comment by kivikakk** [comment]
Disabling normalisation would break CommonMark compatibility, but in the case of the callback it would be fine (and simple) to pass the unaltered label through. PRs happily accepted!

**Comment by chrisbirster** [comment]
I can work on this.

**Comment by kivikakk** [comment]
@chrisbirster Awesome! Let me know when you have something to look at.
