### ISSUE TITLE
Paragraphs in description terms?

### ISSUE THREAD

**Issue by lise-henry** [kivikakk/comrak#144]
Hi, 
I noticed that DescriptionTerm node's inner content contains contains paragraphs. I'm not sure if it should be? At least it's an error if you render it "naively" to XHTML (e.g. for EPUB), i.e. if you have something like

```html
<dt><p>Foo</p></dt>
```

So on the one hand maybe the inner content should not be in a paragraph node; on the other hand it's not a big deal to handle this case in the renderer, and I'm not even sure it really needs to be change in this library.

**Comment by kivikakk** [comment]
Thanks for bringing this to my attention!

I see. It looks like XHTML and HTML differ in this respect; HTML 5 permits any "flow content" inside a `<dt>`, which includes `<p>`, whereas XHTML does not.

That said, given how description list parsing currently works, we won't be producing any _other_ kind of block-level element in a `<dt>` anyway. So this is something we can fix without losing any functionality.

I'll put together a fix and @mention you when it's done!

**Comment by kivikakk** [comment]
This has been fixed in #145 — would you like a new release for this?

**Comment by kivikakk** [comment]
In fact, it's time for a new release anyway. Will prepare one now!

**Comment by kivikakk** [comment]
[`comrak` 0.7.1](https://crates.io/crates/comrak/0.7.1) has been released. Thanks for opening the issue!

**Comment by lise-henry** [comment]
Thank you!

**Comment by kivikakk** [comment]
It's been pointed out I split the options struct up in 660ec92, which makes this release semver breaking (see #147), so I've yanked 0.7.1 and re-released as 0.8.0
