### ISSUE TITLE
0.7.1 was a semver-breaking release

### ISSUE THREAD

**Issue by kornelski** [kivikakk/comrak#147]
`ComrakOptions` struct is incompatible between 0.7.0 and 0.7.1.

**Comment by kivikakk** [comment]
Oof, thanks for that. Will yank and replace with 0.8.0 tomorrow.

**Comment by kornelski** [comment]
Thank you

**Comment by kivikakk** [comment]
Thanks for this. 0.7.1 has been yanked and 0.8.0 tagged and released.
