### ISSUE TITLE
git tag for 0.8.0 is missing

### ISSUE THREAD

**Issue by jcgruenhage** [kivikakk/comrak#148]
hey, void package maintainer for comrak here. I'd like to update comrak, but the git tag is missing, at least here on github. Can you create/push that?

**Comment by jcgruenhage** [comment]
(I know it's basically the same as 0.7.1, but still, a tag would help me avoid hacks in the template for the update)

**Comment by kivikakk** [comment]
Ah, yep, my shell history shows I tried to push the tag, but I hadn't actually made it yet 😬 Fixed, thanks for the heads up!

**Comment by jcgruenhage** [comment]
Thanks! No worries, stuff like this happens all the time ^^
Update is PR'd https://github.com/void-linux/void-packages/pull/23544
