### ISSUE TITLE
Upload binary releases to Github Releases API?

### ISSUE THREAD

**Issue by solderjs** [kivikakk/comrak#153]
I'm trying to find a good markdown command line tool to add to https://webinstall.dev/ and this looks like it would be very good, but there aren't any official releases as far as I can tell (and it's important to have something self-contained that doesn't require a full toolchain in order to install and use).

Would you be open to publishing releases for amd64 Mac & Windows, and also arm64 (RPi) for Linux?

**Comment by kivikakk** [comment]
Hi there! I am totally open to it.

Does arm64 mean ARMv8/aarch64? (I'm pretty new to these architectures.) I have a local RPi 3 (ARMv7) which I've test driven a cross-compile on and it worked well, but I don't have an arm64 device to test on.

I've tried a cross-compile for `aarch64-unknown-linux-gnu` — would you be willing to try it on your device? If so, here it is:

[comrak-aarch64-unknown-linux-gnu.zip](https://github.com/kivikakk/comrak/files/5061653/comrak-aarch64-unknown-linux-gnu.zip)

**Comment by kivikakk** [comment]
I've just got my Windows cross-compile working correctly and tested, so aarch64 is the last piece of the puzzle.

**Comment by kivikakk** [comment]
> I've tried a cross-compile for `aarch64-unknown-linux-gnu` — would you be willing to try it on your device? If so, here it is:
> 
> [comrak-aarch64-unknown-linux-gnu.zip](https://github.com/kivikakk/comrak/files/5061653/comrak-aarch64-unknown-linux-gnu.zip)

I've cobbled together an aarch64 VM, but it just hangs without processing any input 😅 `strace` falls quiet after (what I assume is) the Rust runtime sets up signal handlers.

I'd be curious to know if the same happens for you. Trying to build directly on the VM now.

**Comment by kivikakk** [comment]
This is built directly on the VM. It runs fine, but I'd love to get someone to verify this on actual hardware before attaching it to the release.

[comrak-aarch64-unknown-linux-gnu.zip](https://github.com/kivikakk/comrak/files/5063224/comrak-aarch64-unknown-linux-gnu.zip)

**Comment by solderjs** [comment]
Awesome! I'll dust off my Raspberry Pi 3 and see if it works.

Will you also upload the Linux amd64?

**Comment by kivikakk** [comment]
Yes, done!

I've also uploaded the arm7 binary, which works on my RPi 3 B+ running armv7l. (I could try installing aarch64 on it, but it's used every day and I don't want to commit to the downtime 😅)

Last one is aarch64. I _think_ the second of the two uploads should work, since it was built in and runs on my Debian aarch64 VM. Fingers crossed!

**Comment by solderjs** [comment]
See https://github.com/webinstall/packages/issues/75

And https://beta.webinstall.dev/comrak

You should be able to test installing on various Mac and Linux platforms like so:

```bash
export WEBI_HOST=https://beta.webinstall.dev
curl -fsS https://beta.webinstall.dev/comrak | bash
```

And similarly on Windows.

**Comment by kivikakk** [comment]
> And https://beta.webinstall.dev/comrak

This looks incredible! Thank you so much for your hard work on this!

**Comment by kivikakk** [comment]
0.8.2 is released and has the full set of binaries attached: https://github.com/kivikakk/comrak/releases/tag/0.8.2

**Comment by solderjs** [comment]
Thanks so much for all your work on this. I'm glad to finally have a lightweight markdown option.

**Comment by solderjs** [comment]
P.S. What does `comrak` mean and how to you pronounce it?

**Comment by kivikakk** [comment]
Awesome! I'm really glad for the build process changes that've resulted from your opening this issue — I now actually have a checklist for making releases consistently — so thank you.  Will close out this issue now.
