### ISSUE TITLE
.comrakrc for cli default options?

### ISSUE THREAD

**Issue by solderjs** [kivikakk/comrak#155]
I think the most common use case for the CLI would be to do something like this:

```bash
comrak --unsafe --gfm --github-pre-lang --header-ids '' README.md
```

However, that's quite a bit to type.

Do you think it would be good to add the functionality of reading default options from `$HOME/.config/comrak/config` or `$HOME/.comrakrc`?

If not, I suppose that an alias such this would be a good workaround:

```bash
alias comrak="comrak --unsafe --gfm --github-pre-lang --header-ids ''"
```

**Comment by kivikakk** [comment]
I am a little hesitant to add a config file; I'm imagining that (e.g.) someone putting `--gfm` in their config file then might want a `--no-gfm` CLI option to override the setting from config, and things getting a bit fractal from there.

But I would like to make the tool easier to use from the CLI. Perhaps it's enough to have the config file location itself configurable via CLI option, so someone could turn it off with `--config /dev/null` or `--no-config` or similar, and then we wouldn't need a whole lot of `--no-X` override variants.

What do you think? I don't use Comrak from CLI myself (only library) so I'm not coming up with use cases so easily.

**Comment by solderjs** [comment]
I think that would be perfect.

**Comment by kivikakk** [comment]
Excellent. I'll get this going tonight and ask for your feedback when done :)

**Comment by kivikakk** [comment]
I should note — I would strongly caution against adding `--unsafe` to any kind of default config file. See https://github.com/github/cmark-gfm/pull/123 and https://github.com/commonmark/cmark/commit/325a1471d2a32bcc1e2d2580b973ff4ba1df85e8 where we moved to this posture across the core CommonMark and GFM libraries.

**Comment by solderjs** [comment]
> I would strongly caution against adding`--unsafe` to any kind of default config file

I completely agree for a web or programming API where data is being received from users, or for a command that's being called from such a service.

When considering documents that I create on my own local computer, however, markdown is just a shortcut for HTML, and it's quite often that I want HTML, and possibly even little toy scripts for demoing widgets, in the output page.

**Comment by kivikakk** [comment]
👍  Makes total sense.
