### ISSUE TITLE
Should this support gfm frontmatter?

### ISSUE THREAD

**Issue by solderjs** [kivikakk/comrak#156]
I don't know if cmark supports this, but I know that Github itself does.

I'm not suggesting that `comrak` _should_ support markdown frontmatter, but I'm curious as to whether or not it was intended to follow the same behavior.

# Github Behavior

If I have a file like this on Github:

~~~mkdn
----
foo: bar
baz: foo
----

What's up?

yo yo yo

```bash
hey
```
~~~

 it will produce a table:

~~~html
<table data-table-type="yaml-metadata">
  <thead>
  <tr>
  <th>foo</th>
  <th>baz</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td><div>bar</div></td>
  <td><div>foo</div></td>
  </tr>
  </tbody>
</table>
<p>What's up?</p>
<p>yo yo yo</p>
<pre lang="bash"><code>hey
</code></pre>
~~~

But the comrak output does not create the table and, in fact, creates an `h2` instead:

~~~html
<hr />
<h2><a href="#foo-bar-baz-foo" aria-hidden="true" class="anchor" id="foo-bar-baz-foo"></a>foo: bar
baz: foo</h2>
<p>What's up?</p>
<p>yo yo yo</p>
<pre lang="bash"><code>hey
</code></pre>
~~~

**Comment by kivikakk** [comment]
Hey! Thanks for submitting the issue.

In general, Comrak tries to do exactly what [cmark-gfm](https://github.com/github/cmark-gfm) does; we've added small bits of other functionality on top of what cmark-gfm can do, but in general I'd like to keep the scope to match the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/), which itself is a superset of the [CommonMark Spec](https://spec.commonmark.org/0.29/).

The extent of both tools is to convert GFM or CommonMark Spec-compliant Markdown into HTML. The intent is that you would then postprocess HTML as necessary, e.g. to add @mentions, convert links like `https://github.com/kivikakk/diesel_ltree/pull/9` into friendly-looking links like https://github.com/kivikakk/diesel_ltree/pull/9, or do sanitisation (e.g. remove disallowed CSS classes).

YAML front matter isn't a part of the GFM spec — in fact it's captured by a _pre_-processing step in GitHub's own HTML pipeline, extracted before it ever hits cmark-gfm.

I think this answers the question of _intent_ — it's not intended that Comrak support YAML front matter. We could add support (with a flag) to convert it into a table similarly, but imo it's not exactly super _helpful_ to do so, or at least not generally helpful? It would also add a YAML dependency to Comrak, which I don't love.

**Comment by Xe** [comment]
Feel free to borrow this code to do that: https://github.com/Xe/site/blob/master/src/post/frontmatter.rs
