### ISSUE TITLE
Don’t use regular expressions

### ISSUE THREAD

**Issue by DemiMarie** [kivikakk/comrak#16]
Currently the [`scanners.rs`][scanners] file uses the `regex` crate.  This means that it is slower than the re2c-generated scanners in cmark.

Instead, the code should be written by hand.

[scanners]: https://github.com/kivikakk/comrak/blob/37d4f54e831c89b5d0748b0ec947b66eae32da06/src/scanners.rs

**Comment by kivikakk** [comment]
:+1: on this. I'll look into doing this soon.

**Comment by DemiMarie** [comment]
One could also use one of the DFA-generating tools available.  Most require nightly Rust, but they should at least be benchmarked.

**Comment by kivikakk** [comment]
@DemiMarie do you have any particular suggestions? I've had a look around and haven't found anything obviously usable.

**Comment by kivikakk** [comment]
I'm going to benchmark https://github.com/goffrie/plex. It requires nightly, and I would like this library to still work on stable, but it would still be an interesting datapoint.

**Comment by kivikakk** [comment]
Doing a test rewrite with [pest](https://crates.io/crates/pest) instead.

**Comment by kivikakk** [comment]
Compile times are up maybe to about ~1.5x what they were. I'm unable to see much of a difference in actual results, however:

* cmark-gfm:
  mean = 0.9495, median = 0.9400, stdev = 0.0296
* comrak master:
  mean = 2.4245, median = 2.4200, stdev = 0.0548
* comrak pest:
  mean = 2.4045, median = 2.3800, stdev = 0.0765

The code is likely cleaner this way so I may merge it anyway.

**Comment by kivikakk** [comment]
Results when taken on a Linux VM (as opposed to macOS host):

* cmark-gfm:
  mean = 1.2115, median = 1.2000, stdev = 0.0651
* comrak master:
  mean = 1.8600, median = 1.8550, stdev = 0.0640
* comrak pest:
  mean = 1.8570, median = 1.8450, stdev = 0.0667
