### ISSUE TITLE
Should `--gfm` cancel `--unsafe`?

### ISSUE THREAD

**Issue by solderjs** [kivikakk/comrak#160]
Perhaps this is the desired behavior because perhaps that's how `cmark` works, but it is unexpected to me:

Defaults:

```bash
printf 'Hello\n<script>console.log("hello");</script><div>Hello</div>' | comrak
<p>Hello</p>
<!-- raw HTML omitted -->
```

Unsafe:

```bash
printf 'Hello\n<script>console.log("hello");</script><div>Hello</div>' | comrak --unsafe
<p>Hello</p>
<script>console.log("hello");</script><div>Hello</div>
```

GFM:

```bash
printf 'Hello\n<script>console.log("hello");</script><div>Hello</div>' | comrak --gfm
<p>Hello</p>
<!-- raw HTML omitted -->
```

Unsafe GFM:

```bash
printf 'Hello\n<script>console.log("hello");</script><div>Hello</div>' | comrak --unsafe --gfm
<p>Hello</p>
&lt;script>console.log("hello");&lt;/script><div>Hello</div>
```

Escaped

```bash
printf 'Hello\n<script>console.log("hello");</script><div>Hello</div>' | comrak --escape
<p>Hello</p>
&lt;script&gt;console.log(&quot;hello&quot;);&lt;/script&gt;&lt;div&gt;Hello&lt;/div&gt;
```

I would expect that `--unsafe` allows me to use `iframe`s and `script`s.

This is especially odd because `--gfm` only half-escapes the html rather that full escaping it. This almost seems like an order-of-operations error in which either `--unsafe` or `--escape` is applied before `--gfm`, and `--gfm` ignores `--unsafe`.

**Comment by kivikakk** [comment]
It's a bit unintuitive, but `--gfm` enables `--tagfilter` (see <https://github.github.com/gfm/#disallowed-raw-html-extension->), so while `--unsafe` is still working and enabled, the tagfilter takes precedence.

**Comment by solderjs** [comment]
Ahh... very odd since it still allows `<a href="javascript:alert('')">`.

I don't see any option for extensions. Is there a way to enable specific extensions?

**Comment by kivikakk** [comment]
Yeah, I’m not convinced on the usefulness of the feature, to be honest. It is not particularly safe. It might be better that we remove it, especially in light of default-safe anyway. Its inclusion in the spec is an oddity, especially as (iirc) it isn’t implemented in `cmark-gfm` itself.

`-e` enables an extension.

**Comment by solderjs** [comment]
`--tagfilter` + CSP should do the trick:

https://security.stackexchange.com/questions/203340/does-csp-block-javascript-in-a-href-tags

**Comment by solderjs** [comment]
Here we go: https://github.com/webinstall/packages/pull/77

Should have that merged tomorrow after a review from Ryan.
