### ISSUE TITLE
Please `cargo update -p comrak` to 0.9.1+

### ISSUE THREAD

**Issue by kivikakk** [kivikakk/comrak#173]
[comrak 0.9.1](https://github.com/kivikakk/comrak/releases/tag/0.9.1) has been released with a security fix.

Please ensure you update soon, or are otherwise unaffected (e.g. by doing your own sanitisation).

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

The pull request adding it can be found here: https://github.com/RustSec/advisory-db/pull/774

**Comment by kivikakk** [comment]
Thank you!
