### ISSUE TITLE
binary: flag for output: -o ./outfile.txt

### ISSUE THREAD

**Issue by coolaj86** [kivikakk/comrak#176]
If you're using comrak with something like `watchexec` it's awkward to try to wrap the command in bash to get it to work.

**Good**:
```bash
watchexec -- comrak ./input.md -o output.html
```

*Not-so-good*:
```bash
watchexec -- bash -c 'comrak ./input.md > output.html'
```

Especially because if comrak is safely installed to `~/.local/bin` and it is `~/.bashrc` is that puts that in the `PATH`, it won't be available in a non-interactive shell like that.

**Comment by kivikakk** [comment]
Hm, good point. I like the sound of `-o`. I'll implement it shortly.

**Comment by coolaj86** [comment]
Sweet. I look forward to the release! I was doing a little video on Markdown and showcased comrak:

https://youtu.be/iv1pZKH3c-Q

I hope to be able to use it with watchexec in the next one.

**Comment by kivikakk** [comment]
Awesome! I had a quick watch of the video, looks really good. I'll ping you when the release is made.

You might find this resource useful: <https://gist.github.com/kivikakk/622b5dcf395e26c49e2334f0eb19e6f9>

It might be slightly out of date now (only slightly if so). I maintained it when I was maintaining the user content pipeline at GitHub. Particularly handy if you're writing raw HTML in Markdown and wondering why some things are allowed and some aren't!

**Comment by kivikakk** [comment]
Oh, another comment that comes to mind for when you want to embed Markdown in Markdown etc. --- you can use a greater number of backticks than three in fenced code blocks, and then it'll require that many to end it, like this:

``````md
````md
```
test triple backtick in quadra backtick
```
````
``````

Output:

````md
```
test triple backtick in quadra backtick
```
````

Similarly, if you want to use backticks inside code inlines, use multiple backticks: ``` `` example ` one `` ``` produces `` example ` one ``. Note that spaces at the start and end are removed. That makes it possible to e.g. write `` ` `` (``` `` ` `` ```) without any spaces in the result.

**Comment by kivikakk** [comment]
@coolaj86 0.10.0 is available on crates.io, but I don't have access to my x86 Windows machine right now so I can't make the Windows builds yet! I'll push them tomorrow and let you know.

**Comment by kivikakk** [comment]
Snuck it in. Good to go!
