### ISSUE TITLE
Table within list doesn't render correctly

### ISSUE THREAD

**Issue by ajeetdsouza** [kivikakk/comrak#182]
In the README of my crate, a Markdown table placed under a list element doesn't render correctly, even with the correct indentation. This works fine on GitHub, and it would be nice if comrak was able to support this too.

For context, look at the Environment Variables section in both of these:

GitHub README: https://github.com/ajeetdsouza/zoxide#environment-variables
crates.io README (rendered with Comrak): https://crates.io/crates/zoxide

---

**The following is an example of a table within a list in Markdown:**

```markdown
- Root 1
  - Item 1
  - Item 2:
    | OS          | Path                                     | Example                                    |
    | ----------- | ---------------------------------------- | ------------------------------------------ |
    | Linux / BSD | `$XDG_DATA_HOME` or `$HOME/.local/share` | `/home/alice/.local/share`                 |
    | macOS       | `$HOME/Library/Application Support`      | `/Users/Alice/Library/Application Support` |
    | Windows     | `{FOLDERID_RoamingAppData}`              | `C:\Users\Alice\AppData\Roaming`           |
```

**It should render this way:**

- Root 1
  - Item 1
  - Item 2:
    | OS          | Path                                     | Example                                    |
    | ----------- | ---------------------------------------- | ------------------------------------------ |
    | Linux / BSD | `$XDG_DATA_HOME` or `$HOME/.local/share` | `/home/alice/.local/share`                 |
    | macOS       | `$HOME/Library/Application Support`      | `/Users/Alice/Library/Application Support` |
    | Windows     | `{FOLDERID_RoamingAppData}`              | `C:\Users\Alice\AppData\Roaming`           |

**Comment by kivikakk** [comment]
Thanks for the report. It looks like this change needs to be carried across to Comrak: https://github.com/github/cmark-gfm/commit/ef13dc52e19058950bfa5f76d30eda6d355e0c8d

**Comment by ajeetdsouza** [comment]
That was fast, thank you!
