### ISSUE TITLE
markdown inside of unknown html tags is ignored

### ISSUE THREAD

**Issue by toddself** [kivikakk/comrak#185]
When you have html that wraps a markdown tag that comrak doesn't understand you get unexpected results

```markdown
<figure>
![description](image.jpg)
</figure>
```

Using `comrak --escape --smart --unsafe` as the command will output:

```html
&lt;figure&gt;
![description](image.jpg)
&lt;/figure&gt;
```

**Comment by kivikakk** [comment]
This is per CommonMark; [compliant implementations behave this way](https://spec.commonmark.org/dingus/?text=%3Cfigure%3E%0A!%5Bdescription%5D(image.jpg)%0A%3C%2Ffigure%3E). See the relevant part of the spec: <https://spec.commonmark.org/0.29/#html-blocks>

To work around, insert an empty line between the HTML tags and Markdown; or, write out the image tag in HTML yourself.
