### ISSUE TITLE
Single level domain names are not recognized by the autolink extension

### ISSUE THREAD

**Issue by btzy** [kivikakk/comrak#190]
When autolink is enabled (`options.extension.autolink = true;`), text that look like URLs should be converted into links.

This works, as expected: `http://example.com/path/to/my/page`

However, this doesn't: `http://example/path/to/my/page`

The CommonMark spec doesn't seem to require that the domain name must have at least two levels.  However, a single level domain name is a valid URL, and it's common in private networks.

**Comment by kivikakk** [comment]
The GFM spec defines autolinking as enabled by `options.extension.autolink`, and [does mandate at least two levels](https://github.github.com/gfm/#valid-domain):

> A valid domain consists of segments of alphanumeric characters, underscores (_) and hyphens (-) separated by periods (.). There must be at least one period, and no underscores may be present in the last two segments of the domain.

(Any vague or imprecise wording in this section is, unfortunately, mine.)

This is why GitHub itself doesn't support it either; examples: http://example.com/path/to/my/page http://example/path/to/my/page

And look at that — it does! This is literally a bug. The main [autolink spec test](https://github.com/github/cmark-gfm/blob/85d895289c5ab67f988ca659493a64abb5fec7b4/test/extensions.txt#L539-L581) doesn't include a single level domain.

The point of Comrak is to provide spec compatibility with GFM, in a way that's compatible with GitHub. Seeing as it is compliant with all the spec _examples_, and is as correct as the reference implementation, I'm :+1: on making this change.
