### ISSUE TITLE
cli: reduce help text's line length

### ISSUE THREAD

**Issue by frogtile** [kivikakk/comrak#196]

**Comment by frogtile** [comment]
@kivikakk clap has methods to do this. Won't they work?

**Comment by kivikakk** [comment]
Does it? They might! I am not familiar. :) PRs are very welcome.

**Comment by frogtile** [comment]
> Does it? They might! I am not familiar. :) PRs are very welcome.

I am surprised. You are using a library and you aren't willing to know it to fix an issue.

**Comment by kivikakk** [comment]
I direct you to https://github.com/kivikakk/comrak/issues/186#issuecomment-821967841. My time is limited.
