### ISSUE TITLE
Error in s-expression example

### ISSUE THREAD

**Issue by simonh1000** [kivikakk/comrak#201]
The current code does not compile with errors around: https://github.com/kivikakk/comrak/blob/main/examples/s-expr.rs#L55

```
error[E0609]: no field `literal` on type `&Vec<u8>`
  --> src/bin/other.rs:55:51
   |
55 |                     String::from_utf8_lossy(&code.literal),
   |                                                   ^^^^^^^ unknown field

error[E0609]: no field `num_backticks` on type `&Vec<u8>`
  --> src/bin/other.rs:56:26
   |
56 |                     code.num_backticks
   |                          ^^^^^^^^^^^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
```

**Comment by kivikakk** [comment]
👋 Hiya! — I'm not sure what you're building, but it doesn't look quite like comrak:

> ```
>   --> src/bin/other.rs:55:51
> ```

`src/bin/other.rs` is not part of comrak. The s-expr example does work fine, too, in my testing:

```console
$ echo '# hello' | cargo run --example s-expr
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/examples/s-expr`
(Document
    (Heading(NodeHeading { level: 1, setext: false }) "hello")
)
```

**Comment by kivikakk** [comment]
It looks like you're perhaps using the s-expr example as a basis for some of your own work. Could you share your full code? The way you've used it would appear not to be correct; or perhaps, you're depending on an older comrak version than the example code ships with?

**Comment by simonh1000** [comment]
Thanks for replying. I can see that your code does run, when I download a zip of the repo. This is what I did though.

- I took a wasm_bindgen setup - such that my Cargo.toml reads
```
[package]
name = "console_log"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
web-sys = { version = "0.3.55", features = ['console'] }
comrak = "0.10"
```

- I created an `/examples` directory and copied your `s-espr.rs` into that
- then ran `cargo run --example s-expr file1.md` (I have to say I do not understand how example and examples get mapped to each other, but I am a beginner)
- I get the error above

I am indeed using your code as the basis for writing a custom emit function (to a json format we use internally). As I don't need the specific bit of code that won't compile, this is is not blocking me.

**Comment by kivikakk** [comment]
OK, I see now. `s-expr.rs` has changed since 0.10, so the short answer is you were using code written for a newer version than the library you depend upon. If you wanted to try this example again, use [0.10's `s-expr.rs`](https://github.com/kivikakk/comrak/blob/0c7c3c5432d6a533cf5612d2f3465187040c0269/examples/s-expr.rs) or upgrade your `comrak` dependency.

**Comment by simonh1000** [comment]
Ugh - I wasn't trying to use an old version, and have updated to the latest and greatest. All good now, thanks

**Comment by simonh1000** [comment]
Spoke too soon. version 0.12.1 does not work with wasm
```
error: failed to run custom build command for `onig_sys v69.7.1`

Caused by:
  process didn't exit successfully: `/Users/simonhampton/code/remix/simon/rust_markdown_wasm/target/debug/build/onig_sys-3cb3681775ae26dc/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("wasm32-unknown-unknown")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_wasm32-unknown-unknown = None
  CC_wasm32_unknown_unknown = None
  TARGET_CC = None
  CC = None
  CFLAGS_wasm32-unknown-unknown = None
  CFLAGS_wasm32_unknown_unknown = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-I" "/Users/simonhampton/code/remix/simon/rust_markdown_wasm/target/wasm32-unknown-unknown/debug/build/onig_sys-84b93c7e3461fd6a/out" "-I" "oniguruma/src" "-DONIG_DISABLE_DIRECT_THREADING=1" "-DONIG_EXTERN=__attribute__((visibility(\"default\")))" "-o" "/Users/simonhampton/code/remix/simon/rust_markdown_wasm/target/wasm32-unknown-unknown/debug/build/onig_sys-84b93c7e3461fd6a/out/oniguruma/src/regexec.o" "-c" "oniguruma/src/regexec.c"
  cargo:warning=In file included from oniguruma/src/regexec.c:36:
  cargo:warning=oniguruma/src/regint.h:109:10: fatal error: 'stdlib.h' file not found
  cargo:warning=#include <stdlib.h>
  cargo:warning=         ^~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

```

It looks like other people have seen this in other contexts and there is no quick fix. I will go back to 0.10 for the time being

**Comment by simonh1000** [comment]
Just seen that I got the idea to use 0.10 from the README!  But that was lucky, because otherwise I would have run into the issue above immediately and would have had to give up. :-)

**Comment by kivikakk** [comment]
Ahhhhhh, so in the end it _was_ my doing! Thanks for your patience — opened a PR #202 to fix this going forward. 😄

**Comment by kivikakk** [comment]
Hahahaha :heart: True, true.

**Comment by emirror-de** [comment]
For all people that come here when looking for a way to build `comrak` for wasm. I have been able to build comrak `0.12` by adding `CPATH=/usr/include` to my environment variables as [stated in this post](https://github.com/rust-onig/rust-onig/issues/153#issuecomment-856333357)

Hope that helps :-)
