### ISSUE TITLE
Feature Request: Store node position

### ISSUE THREAD

**Issue by oovm** [kivikakk/comrak#203]
I hope to do a bidirectional link jump based on `Ast`, but it seems that there is not enough information.

https://github.com/kivikakk/comrak/blob/7b1f19f2be0de1abf26dbf93ddcba9b653e11fae/src/nodes.rs#L365-L366

How about store position with start and end offset`(usize, usize)` or `lsp_types::Range`

**Comment by kivikakk** [comment]
👍 I'm open to implementations, definitely!
