### ISSUE TITLE
Anchors?

### ISSUE THREAD

**Issue by johnoneil** [kivikakk/comrak#206]
I'm using comrak to render markdown to html but my named anchors are invariably removed.

Here's a snippet of how I'm using comrak (not I am setting the `unsafe_` option to true in the hopes this would allow anchors.

```
let mut comrak_options = comrak::ComrakOptions::default();
comrak_options.render.unsafe_ = true;
let mut comrak_extensions = comrak::ComrakExtensionOptions::default();
comrak_extensions.table = true;
comrak_options.extension = comrak_extensions;
let root = comrak::parse_document_with_broken_link_callback(
  &a,
  markdown,
  &comrak_options,
  None,
);
comrak::format_html(root, &comrak_options, &mut output)?;
```

But markdown with html like the following:

```
<a name="mylink">anchor link to here /a>
```

always renders to `<!-- raw HTML omitted ->`.

Similarly I'd expect all headers to have anchors by default, allowing simple linking.

What am I missing about allowing anchors in rendered HTML? From previous issues I get a strong impression this is supported.

**Comment by kivikakk** [comment]
You're including raw HTML in your Markdown source, so you'll need to set `unsafe_` to true for it to not be filtered. The only alternative presently is automatically-generated anchors from the header IDs option.

**Comment by johnoneil** [comment]
Thanks for that @kivikakk . I believe I'm correctly setting the `unsafe_` member correctly, so I suspect either i'm doing something wrong somewhere else or there's a bug in this area.
I can't isolate this in a minimal case at present, so I'm just going to close this. Will reopen if I can take the time to reproduce.

**Comment by johnoneil** [comment]
That worked great @kivikakk . Issue was there was a code path not correctly setting `comak_options.render.unsafe_ = true` that was nonobvious. Can remain closed.
