### ISSUE TITLE
Possibly, incorrect parsing of `\n`

### ISSUE THREAD

**Issue by mikeando** [kivikakk/comrak#209]
The spec has:

> A [code span](https://spec.commonmark.org/0.30/#code-span) begins with a backtick string and ends with a backtick string of equal length. The contents of the code span are the characters between these two backtick strings, normalized in the following ways:
>
> * First, [line endings](https://spec.commonmark.org/0.30/#line-ending) are converted to [spaces](https://spec.commonmark.org/0.30/#space).
> * If the resulting string both begins and ends with a [space](https://spec.commonmark.org/0.30/#space) character, but does not consist entirely of [space](https://spec.commonmark.org/0.30/#space) characters, a single [space](https://spec.commonmark.org/0.30/#space) character is removed from the front and back. This allows you to include code that begins or ends with backtick characters, which must be separated by whitespace from the opening or closing backtick strings.

This means that `\n` should convert to `<code> </code>`, which is the output from the  commonmark.js dingus (https://spec.commonmark.org/dingus/?text=%60%0A%60%0A).

 With`comrak` it is instead converted to `<code></code>`. 
I think this makes no difference in the appearance of the final output - but IMO it would be preferable to strictly match the
expected output.

**Comment by kivikakk** [comment]
Interesting, nice discovery! Would happily accept a patch that addressed this. :blush:

**Comment by mikeando** [comment]
I'd be happy to try to come up with a fix.
Any pointers on where to start? (I've used comrak a bit, but never dug through the code in any detail)

**Comment by mikeando** [comment]
Turned out pretty easy to find: have created PR for it at https://github.com/kivikakk/comrak/pull/210

**Comment by mikeando** [comment]
The PR is merged, this can be closed.
