### ISSUE TITLE
Disabling parser rules

### ISSUE THREAD

**Issue by silverpill** [kivikakk/comrak#244]
Is it possible to skip parsing of certain elements, such as headings or lists?
In my application I need to support only a subset of GFM. The workaround I'm currently using is re-rendering of certain AST nodes back to markdown and replacing them with text nodes, but perhaps there's a better way?

**Comment by kivikakk** [comment]
There is no such feature at present, though I imagine it might not be too hard to add checks at key places in the parser where certain elements are recognised. Pull requests welcome!
