### ISSUE TITLE
Code syntax highlighting is too slow

### ISSUE THREAD

**Issue by pinpox** [kivikakk/comrak#247]
I'm using comrak in a rocket web application together with tera templates. It works fine, but the code syntax highlighting is too slow to be usable. 

This is the relevant code:
```rust
pub fn markdown_filter(value: &Value, _: &HashMap<String, Value>) -> Result<Value> {
    let s = try_get_value!("markdown_filter", "value", String, value);
    let adapter = SyntectAdapter::new("base16-ocean.dark");
    let mut plugins = ComrakPlugins::default();
    plugins.render.codefence_syntax_highlighter = Some(&adapter);
    let outstring = markdown_to_html_with_plugins(&s, &ComrakOptions::default(), &plugins);
    Ok(to_value(&outstring).unwrap())
}
```
Rendering a page that will apply that function to 10 short posts takes **3.4 seconds** on my modern notebook, which makes it too slow to be used in a request handler.

For comparison, using comrak without the plugins like so:
```rust
pub fn markdown_filter(value: &Value, _: &HashMap<String, Value>) -> Result<Value> {
    let s = try_get_value!("markdown_filter", "value", String, value);
    let outstring = markdown_to_html(&s, &ComrakOptions::default());
    Ok(to_value(&outstring).unwrap())
}
```
Is very fast and renders the same page in ~200ms. 

Can something be done to make syntax highlighting perform better?

**Comment by kivikakk** [comment]
I'm sure it can! For a slowdown of that magnitude it's probably an obvious fix. I suspect it might be in the initial Syntect loading process — you could check that by using the same first function but then don't actually call the `_with_plugins` variant and see how fast it is. If so, you likely just need to cache the adapter/plugins. Otherwise, it'll take some profiling.

Unfortunately I don't have the time to check this out myself right now, but with any luck this has given you some direction to keep searching!

**Comment by Ericarthurc** [comment]
@pinpox place your SyntectAdapter in a lazy_static! {} macro
It will speed things up A LOT!

```rs
lazy_static! {
    static ref SYNTECT_ADAPTER: SyntectAdapter<'static> = SyntectAdapter::new("base16-ocean.dark");
}

pub fn markdown_filter(value: &Value, _: &HashMap<String, Value>) -> Result<Value> {
    let s = try_get_value!("markdown_filter", "value", String, value);
    let mut plugins = ComrakPlugins::default();
    plugins.render.codefence_syntax_highlighter = Some(&*SYNTECT_ADAPTER);
    let outstring = markdown_to_html_with_plugins(&s, &ComrakOptions::default(), &plugins);
    Ok(to_value(&outstring).unwrap())
}
```

**Comment by Ericarthurc** [comment]
Or you can use OnceCell to do this as well

**Comment by kivikakk** [comment]
Hi @pinpox — just checking in with this one. Did the suggestions above help you out at all?
