### ISSUE TITLE
Generated footnote html different from cmark-gfm

### ISSUE THREAD

**Issue by digitalmoksha** [kivikakk/comrak#259]
I've started doing some testing between `comrak` and `cmark-gfm`.

I've noticed that the footnote extension generates different html. In particular, `data-footnote-ref`, `data-footnotes`, `data-footnote-backref`, and `aria-label` attributes are no longer added.

**input**

```markdown
1. one[^1]
[^1]: AbC
```

**cmark-gfm output**

```html
<ol>
<li>one<sup class="footnote-ref"><a href="#fn-1" id="fnref-1" data-footnote-ref>1</a></sup></li>
</ol>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>AbC <a href="#fnref-1" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```

**comrak output**

```html
<ol>
<li>one<sup class="footnote-ref"><a href="#fn1" id="fnref1">1</a></sup></li>
</ol>
<section class="footnotes">
<ol>
<li id="fn1">
<p>AbC <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

I also notice the footnote ids no longer use a `-`, such as `fn-1` vs `fn1`

Are these changes by design, or missing implementation?

**Comment by digitalmoksha** [comment]
If it's missing implementation I can put together a PR, but if it's by design I won't worry about it.

**Comment by kivikakk** [comment]
Not by design — when first implemented it was 1:1, but it looks like GitHub have since added these attributes: https://github.com/github/cmark-gfm/pull/234

Happy to accept PRs that realign.

**Comment by kivikakk** [comment]
With the merge of #273, we're a lot closer. There's a few smaller things:

* As @froh mentioned in #271, the footnote label content can differ. We should align this.
* As noted at https://github.com/kivikakk/comrak/pull/273#issuecomment-1403056774, there are some other differences in the IDs generated and the acceptable characters in labels. These should also be aligned. (This is currently causing spec failure in CI.)

**Comment by digitalmoksha** [comment]
Currently `comrak` sequentially numbers footnotes, while `cmark-gfm` utilizes the footnote name.  For example:

```
first[^1] and second[^😄second] and twenty[^_twenty]

[^1]: one
[^😄second]: two
[^_twenty]: twenty
```

in `comrak`

```
<p>first<sup class="footnote-ref"><a href="#fn-1" id="fnref-1" data-footnote-ref>1</a></sup> and second<sup class="footnote-ref"><a href="#fn-2" id="fnref-2" data-footnote-ref>2</a></sup> and twenty[^_twenty]</p>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>one <a href="#fnref-1" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
<li id="fn-2">
<p>two <a href="#fnref-2" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```

and in `cmark-gfm`

```
<p>first<sup class="footnote-ref"><a href="#fn-1" id="fnref-1" data-footnote-ref>1</a></sup> and second<sup class="footnote-ref"><a href="#fn-%F0%9F%98%84second" id="fnref-%F0%9F%98%84second" data-footnote-ref>2</a></sup> and twenty<sup class="footnote-ref"><a href="#fn-_twenty" id="fnref-_twenty" data-footnote-ref>3</a></sup></p>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-1">
<p>one <a href="#fnref-1" class="footnote-backref" data-footnote-backref data-footnote-backref-idx="1" aria-label="Back to reference 1">↩</a></p>
</li>
<li id="fn-%F0%9F%98%84second">
<p>two <a href="#fnref-%F0%9F%98%84second" class="footnote-backref" data-footnote-backref data-footnote-backref-idx="2" aria-label="Back to reference 2">↩</a></p>
</li>
<li id="fn-_twenty">
<p>twenty <a href="#fnref-_twenty" class="footnote-backref" data-footnote-backref data-footnote-backref-idx="3" aria-label="Back to reference 3">↩</a></p>
</li>
</ol>
</section>
```

Will see if I can generate a fix.

**Comment by digitalmoksha** [comment]
I opened separate issues, https://github.com/kivikakk/comrak/issues/307 and https://github.com/kivikakk/comrak/issues/306.

I think we can close this one.
