### ISSUE TITLE
Arena-tree 0.3.0 is yanked, and now I can't compile comrak.

### ISSUE THREAD

**Issue by ivanceras** [kivikakk/comrak#27]
```    
Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `arena-tree` found (required by `comrak`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.3.0
```
Checking arena-tree in crates.io and found out that all versions are yanked.
Now, cargo should STILL be able to download it, however this is not the case.

[arena-tree](https://crates.io/crates/arena-tree/versions) has been yanked since May 24, 2015, but I don't get why comrak still able to compile it in [travis-ci](https://travis-ci.org/kivikakk/comrak/jobs/255144307)

```log
error[E0432]: unresolved import `comrak::format_html`
  --> src/lib.rs:11:30
   |
11 | use comrak::{parse_document, format_html, ComrakOptions};
   |                              ^^^^^^^^^^^ no `format_html` in the root

error[E0432]: unresolved import `comrak::nodes::AstNode`
  --> src/lib.rs:12:21
   |
12 | use comrak::nodes::{AstNode, NodeValue, NodeHtmlBlock};
   |                     ^^^^^^^ Could not find `nodes` in `comrak`

error[E0432]: unresolved import `comrak::nodes::NodeValue`
  --> src/lib.rs:12:30
   |
12 | use comrak::nodes::{AstNode, NodeValue, NodeHtmlBlock};
   |                              ^^^^^^^^^ Could not find `nodes` in `comrak`

error[E0432]: unresolved import `comrak::nodes::NodeHtmlBlock`
  --> src/lib.rs:12:41
   |
12 | use comrak::nodes::{AstNode, NodeValue, NodeHtmlBlock};
   |                                         ^^^^^^^^^^^^^ Could not find `nodes` in `comrak`

error[E0560]: struct `comrak::ComrakOptions` has no field named `ext_tasklist`
  --> src/lib.rs:97:9
   |
97 |         ext_tasklist: true,
   |         ^^^^^^^^^^^^^ `comrak::ComrakOptions` does not have this field

error[E0560]: struct `comrak::ComrakOptions` has no field named `ext_superscript`
  --> src/lib.rs:98:9
   |
98 |         ext_superscript: false,
   |         ^^^^^^^^^^^^^^^^ `comrak::ComrakOptions` does not have this field

error: aborting due to 6 previous errors

error: Could not compile `spongedown`.

To learn more, run the command again with --verbose.
```
I was able to keep building my code since yesterday, something might be a bit off in my machine. But I don't know what.

**Comment by kivikakk** [comment]
Yikes. Thanks for the heads up, I'll get a workaround going.

**Comment by kivikakk** [comment]
(I don't think those are the dates they were yanked; I think those were the original publish dates. Note 0.1.0 is May 20, 2015, and 0.2.0 and 0.3.0 are both May 24.)

**Comment by ivanceras** [comment]
I did an `rm -rf ~/.cargo` and reinstalling via rustup and somehow fix the issues. I think this could be cargo or rustup issues. I remember I did a `rustup self update` and `rustup update` yesterday. That may have the cause of cargo going bonkers after the next reboot.

**Comment by kivikakk** [comment]
Ohhh, I understand now! Of course, the yanked packages will still work for the already-released comrak package (and in dev) — that's the point of yanking being the mechanism instead of deleting. I'll still have to fix this before I can release a new version of comrak to crates.io!

**Comment by ivanceras** [comment]
I think I know now how the problem arise. After removing `~/.cargo` and reinstalling rust. 
Doing a `cargo update` will downgrade the comrak version to 0.1.0
```sh
 Updating registry `https://github.com/rust-lang/crates.io-index`
    Removing arena-tree v0.3.0
    Updating byteorder v1.0.0 -> v1.1.0
    Updating comrak v0.1.4 -> v0.1.0
```
At this point, maybe `cargo` realized that `comrak` should be `v0.1.0` since that's the only version that doesn't depend on the yanked arena-tree.

**Comment by kivikakk** [comment]
I've published ~0.1.5~ 0.1.6 (with fixed tests), which drops the dependency.

**Comment by kivikakk** [comment]
(Let me know if `cargo update` "solves" this for you, and we can close the issue out!)

**Comment by ivanceras** [comment]
Yep, it is building correctly now. Thanks for that quick fix.
