### ISSUE TITLE
feature request: `Ast` to include the offset of the node

### ISSUE THREAD

**Issue by felipesere** [kivikakk/comrak#270]
👋 I'm experimenting with something like `jq` or `yq` but for markdown. 
For that, I turn the stream of `Ast` nodes back into a tree shape that resembles the structure of the document itself.
To make my life easier, it would be great for a given `Ast`, I knew the offset/column where it started.

For examples:
```md
 * [ ] This is a todo
   * [ ] deeper
     * [ ] even
   but what is here?
 * [ ] Are 🔼 separate?
```
In the above example, the `TaskItem` are all in the correct parent/child relationship.
But in the children of  the `* [ ] even` node I get a `Softbreak` and a `Text("but what is here?")`
So my tree roughly resembles:
```md
 * [ ] This is a todo
   * [ ] deeper
     * [ ] even
         but what is here?
 * [ ] Are 🔼 separate?
``` 

I _think_ that the only way for me to tell where that `Text(...)` belongs is by keeping track of the indentation?
I'd be happy to contribute a PR for this.

**Comment by felipesere** [comment]
I've been looking into this and it seems tricky 😅
Is there a chance I could get pointers?

**Comment by kivikakk** [comment]
There's some WIP at #232 which I'll (hopefully!) get back to shortly; it should fulfil this.
