### ISSUE TITLE
does comrak allow spaces in footnote labels?  cmark-gfm doesn't.

### ISSUE THREAD

**Issue by froh** [kivikakk/comrak#271]
[it looks like comrak allows space characters ` ` in footnote labels](https://github.com/kivikakk/comrak/blob/2e219a94c61407df1213e8ad1917bac3b8cb7a67/src/lexer.pest#L35)

[cmark-gfm excludes ` ` space from footnote labels](https://github.com/github/cmark-gfm/blob/6a6e335709ef68cf2c616eeaf61b09ed4c654669/src/scanners.re#L323)

**Comment by digitalmoksha** [comment]
@froh I think this is fixed now with the latest commits on `main`

```
one[^foo bar]
[^foo bar]: test
```

now yields

```
<p>one[^foo bar]
[^foo bar]: test</p>
```

for both `cmark-gfm` and `comrak`

**Comment by kivikakk** [comment]
Yep, that's right; thanks @digitalmoksha! And thanks @froh for the report.
