### ISSUE TITLE
Code blocks nested inside <details> tags don't get rendered properly

### ISSUE THREAD

**Issue by illicitonion** [kivikakk/comrak#277]
I would expect to be able to write:

````
<details><summary>Click to expand</summary>
```go
if x > y {
    fmt.Println("Great")
}
```
</details>
````

and end up with a collapsed section with some syntax-highlighted monospace code.

However, this doesn't end up rendering the code block as a code block:

<details><summary>Click to expand</summary>
```go
if x > y {
    fmt.Println("Great")
}
```
</details>

I can work around this by using a `<pre>` tag instead of a code-block:

<details><summary>Click to expand</summary>
<pre>
if x > y {
    fmt.Println("Great")
}
</pre>
</details>

at the expense of syntax highlighting.

Worse still, if there's an empty newline in the middle of the code block, the `</details>` tag and any text after it get collapsed into the `<details>` tag as well:

````
<details><summary>Click to expand the full output of the exit codes section of `man curl`</summary>
```
Before newline

After newline
```
</details>

This text gets swallowed
```

(I'm handily relying in this issue on the fact that GitHub renders its markdown via this crate, but https://github.com/illicitonion/repro-github-markdown-2023-details-with-verbatim/blob/main/README.md has sample input too)

**Comment by kivikakk** [comment]
This is per the spec ([see example](https://spec.commonmark.org/dingus/?text=%3Cdetails%3E%3Csummary%3EClick%20to%20expand%3C%2Fsummary%3E%0A%60%60%60go%0Aif%20x%20%3E%20y%20%7B%0A%20%20%20%20fmt.Println(%22Great%22)%0A%7D%0A%60%60%60%0A%3C%2Fdetails%3E)). A newline after the `</summary>` will correct it.
