### ISSUE TITLE
Code blocks contain invalid preceding and trailing newlines

### ISSUE THREAD

**Issue by AlexApps99** [kivikakk/comrak#278]
````markdown
```rust
fn foo() {}
```
````
currently generates
```html
<pre style="background-color:#2b303b;"><code class="language-rust">
<span style="color:#b48ead;">fn </span><span style="color:#8fa1b3;">foo</span><span style="color:#c0c5ce;">() {}
</span>
</code></pre>
```
rather than
```html
<pre style="background-color:#2b303b;"><code class="language-rust"><span style="color:#b48ead;">fn </span><span style="color:#8fa1b3;">foo</span><span style="color:#c0c5ce;">() {}</span></code></pre>
```

This causes an extra newline at the start and end of each code block. This happens in the CLI and the library.

Current behaviour:
![image](https://user-images.githubusercontent.com/30854646/218685293-83d29207-2bd3-421d-a3b3-41a3c72618b9.png)
Correct behaviour:
![image](https://user-images.githubusercontent.com/30854646/218685379-26ddc86e-3e01-4709-b217-ca81b29b24d6.png)

**Comment by kivikakk** [comment]
Thanks so much for this report — you're absolutely right. I'll push a fix shortly, though I'm not sure when I'll next be able to make a release.
