### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by SSJohns** [kivikakk/comrak#28]
In light of the speed problems I was probably going to make a benchmarking suite to test what general changes did to the overall speed. I wanted to ask if you had any particular areas that you wanted tested or evaluated that I should include.

**Comment by kivikakk** [comment]
`src/scanners.rs` seems like a big offender (per #25); other than that I'm generally concerned about indirection through `RefCell`, and as @DemiMarie suggests, string copies. I haven't got other particular areas of concern, though I'll be doing some more benching today.

**Comment by kivikakk** [comment]
`find_special_char` takes up almost 25% of runtime on large documents, it seems.
