### ISSUE TITLE
MSRV bump in 0.17.0

### ISSUE THREAD

**Issue by silverpill** [kivikakk/comrak#290]
In one of the recent commits, `#[default]` enum variants were introduced: https://github.com/kivikakk/comrak/commit/22aeda8ae21d3c506ce1de878825a7510357b873#diff-78fae44774dfd69260e925a4e3a4451540188d722d41690c98e75521a9b2c8c3R247
This feature requires Rust 1.62, but otherwise comrak library seems to be compatible with Rust 1.5~ (I'm using it with Rust 1.56).
If it is possible to delay MSRV increase a bit, I would appreciate that.

(This issue is specifically about library; the binary probably has higher MSRV already due to `clap` dependency)

**Comment by kivikakk** [comment]
Hi there!

Yes, I'm happy to do this — would you be able to open the PR for the change? Otherwise I'll get to it in a bit.

**Comment by kivikakk** [comment]
0.18 will land later today with #293 merged — I'll bump (and close) this issue when it's out!

**Comment by kivikakk** [comment]
This is done!

**Comment by silverpill** [comment]
Thanks!
One more question. I'm trying to figure out how to modify my code in line with v0.18.0 API changes (https://github.com/kivikakk/comrak/commit/a11a4d48d82f83f54224903e77bbe18d6dc71a6d). I used `Ast::new(<nodevalue>)` to replace nodes in existing document and add new ones, but now this constructor requires `an argument of type LineColumn`. How line and column should be determined?

**Comment by kivikakk** [comment]
The nodes you're replacing will have the value you want — `node.data.borrow().sourcepos.start`.

**Comment by silverpill** [comment]
@kivikakk What about adding new nodes? For, example, pre 0.18.0 it was possible to do the following:

```rust
let text_node_value = NodeValue::Text(mytext);
let text_node = arena.alloc(AstNode::from(text_node_value));
node.append(text_node);
```

In 0.18.0, `AstNode` doesn't implement `From<NodeValue>`. One can create it with `Node::new(RefCell::new(Ast::new(value, ?)))` but it is not clear what should be the starting position.

**Comment by kivikakk** [comment]
Hmm, yeah, it's not too ergonomic to be forced to come up with a value for that, is it? I think I might add a `Default` implementation that Just Works:tm: to make this easier. For now try `(0, 1).into()`.

**Comment by silverpill** [comment]
I'm just curious about possible side-effects of choosing a value for the `start` parameter in `Ast::new`. If there are no side-effects, maybe an alternative constructor can be added, e.g. `Ast::new_at_0(value: NodeValue)`?  Or maybe this is simply a documentation issue - I'm not sure.

I'll try `(0, 1).into()`, thank you!

**Comment by kivikakk** [comment]
Yeah, it's a bit tricky to summarise; the side-effects might depend on what kinds of nodes you're creating and nesting.

I'm also thinking that perhaps putting `sourcepos` stuff behind a feature flag might be a good idea, for those who don't care and don't want to think about it when custom-building ASTs.
