### ISSUE TITLE
Description lists with tight and loose syntax

### ISSUE THREAD

**Issue by digitalmoksha** [kivikakk/comrak#327]
What do you think about supporting the tight and loose syntax as laid out by `jgm` in https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/definition_lists.md?

This follows the style of lists in general, where a tight list doesn't wrap the content in a paragraph, and the loose list does. So this would be valid

```
one
: two
: three
```

and generate this

```
<dl>
<dt>one</dt>
<dd>two
</dd>
<dd>three
</dd>
</dl>
```

and this would be valid

```
one

: two

: three
```

and generate this

```
<dl>
<dt>one</dt>
<dd>
<p>two</p>
</dd>
<dd>
<p>three</p>
</dd>
</dl>
```

I think what is there currently is mostly a subset of that spec.  The spec adds a tight list (no blank line necessary), support for `~` as a marker, and allows for multiple definitions for each term.

**Comment by kivikakk** [comment]
SGTM — I like the idea of making the tight/loose distinction more widely used, since it's a bit obscure as it is and is often a source of confusion.
