### ISSUE TITLE
CVE advisory in upstream cmark-gfm

### ISSUE THREAD

**Issue by gjtorikian** [kivikakk/comrak#334]
https://github.com/github/cmark-gfm/security/advisories/GHSA-w4qg-3vf7-m9x5

The diff/fix: https://github.com/github/cmark-gfm/compare/0.29.0.gfm.11...0.29.0.gfm.12#diff-013fac9bd58a7cb5ff9ac3b1f3e52ecedea83f1cfeff2ff2e23fdc40f2326cfe

**Comment by charlottia** [comment]
@digitalmoksha If I am not mistaken, #343 fixes this?

**Comment by digitalmoksha** [comment]
@charlottia yes, #343 fixes the CVE
