### ISSUE TITLE
[GFM] Alerts

### ISSUE THREAD

**Issue by sanpii** [kivikakk/comrak#352]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by gjtorikian** [comment]
This project aims to be [GFM-spec compliant](https://github.github.com/gfm/) and is unlikely to add additional extensions/features outside of it. You can try using an HTML postprocessor to decorate the final HTML however you like.
