### ISSUE TITLE
Lists not exitable

### ISSUE THREAD

**Issue by Flemmli97** [kivikakk/comrak#357]
When writing a list you cannot "exit" the list anymore
Example
```
* A
* B
C
```

will output to something like 
```
* A
* B C
```

You can only add new lines with further list items.

calling it with simply 
```rust
markdown_to_html(
        "* A\n* B\nC",
        &comrak::Options::default(),
    )
```

**Comment by digitalmoksha** [comment]
That's how the syntax of CommonMark works. You will need a blank line after the last item to escape the list. 

See how it behaves in the CommonMark dingus, https://spec.commonmark.org/dingus/?text=*%20A%0A*%20B%0AC%0A

**Comment by gjtorikian** [comment]
Since this complies to the spec, I am closing this issue.☮️

**Comment by kivikakk** [comment]
Thank you all! 🤍
