### ISSUE TITLE
Width options usage ?

### ISSUE THREAD

**Issue by Its-Just-Nans** [kivikakk/comrak#361]
Hello,

How can I use the --width options in the CLI ?

With and without the options, the output isn't different ?!

```sh
cargo install comrak

comrak --gfm -o index_0.html README.md
comrak --gfm -o index_1.html --width 50 README.md

diff index_*.html
# no difference
```

**Comment by kivikakk** [comment]
Presently the `--width` option only applies to the CommonMark output mode.
