### ISSUE TITLE
nested lists not rendering properly

### ISSUE THREAD

**Issue by crowlKats** [kivikakk/comrak#365]
it seems nested lists arent actually nesting, and are just flat

with comrak:
<img width="605" alt="Screenshot 2024-02-10 at 14 16 31" src="https://github.com/kivikakk/comrak/assets/13135287/65c79361-5c97-41b7-bd0b-a6ae0f909e1d">

with deno-gfm:
<img width="587" alt="Screenshot 2024-02-10 at 14 16 38" src="https://github.com/kivikakk/comrak/assets/13135287/79374dc9-2665-4cb8-8b0b-fba59ee9a6be">

md used:
```
## Differences with zx

1. Cross platform shell.
  - Makes more code work on Windows.
  - Allows exporting the shell's environment to the current process.
  - Uses [deno_task_shell](https://github.com/denoland/deno_task_shell)'s parser.
1. Minimal globals or global configuration.
  - Only a default instance of `$`, but it's not mandatory to use this.
1. No custom CLI.
1. Good for application code in addition to use as a shell script replacement.
1. Named after my cat.
```

**Comment by kivikakk** [comment]
As always, a good start is to try the official [commonmark dingus](https://spec.commonmark.org/dingus/?text=%23%23%20Differences%20with%20zx%0A%0A1.%20Cross%20platform%20shell.%0A%20%20-%20Makes%20more%20code%20work%20on%20Windows.%0A%20%20-%20Allows%20exporting%20the%20shell%27s%20environment%20to%20the%20current%20process.%0A%20%20-%20Uses%20%5Bdeno_task_shell%5D(https%3A%2F%2Fgithub.com%2Fdenoland%2Fdeno_task_shell)%27s%20parser.%0A1.%20Minimal%20globals%20or%20global%20configuration.%0A%20%20-%20Only%20a%20default%20instance%20of%20%60%24%60%2C%20but%20it%27s%20not%20mandatory%20to%20use%20this.%0A1.%20No%20custom%20CLI.%0A1.%20Good%20for%20application%20code%20in%20addition%20to%20use%20as%20a%20shell%20script%20replacement.%0A1.%20Named%20after%20my%20cat.). You'll note comrak matches its output; deno-gfm is not quite right here.

See the [CommonMark spec](https://spec.commonmark.org/0.31.2/#list-items) on list items. tl;dr your sublists aren't indented enough to be considered a continuation of the ordered list items. Try this:

```markdown
## Differences with zx

1. Cross platform shell.
   - Makes more code work on Windows.
   - Allows exporting the shell's environment to the current process.
   - Uses [deno_task_shell](https://github.com/denoland/deno_task_shell)'s parser.
1. Minimal globals or global configuration.
   - Only a default instance of `$`, but it's not mandatory to use this.
1. No custom CLI.
1. Good for application code in addition to use as a shell script replacement.
1. Named after my cat.
```

Output (GitHub is CommonMark compliant, like comrak, so we can just use it to test):

> ## Differences with zx
> 
> 1. Cross platform shell.
>    - Makes more code work on Windows.
>    - Allows exporting the shell's environment to the current process.
>    - Uses [deno_task_shell](https://github.com/denoland/deno_task_shell)'s parser.
> 1. Minimal globals or global configuration.
>    - Only a default instance of `$`, but it's not mandatory to use this.
> 1. No custom CLI.
> 1. Good for application code in addition to use as a shell script replacement.
> 1. Named after my cat.
