### ISSUE TITLE
Deprecation of arena_tree

### ISSUE THREAD

**Issue by SSJohns** [kivikakk/comrak#39]
I'm not sure if this is a real issue, but arena_tree is no longer maintained by word from the author [here](https://github.com/SimonSapin/rust-forest/issues/6). He has said that he would be willing to give it over to a maintainer if someone would step up, but I doubt that's happening anytime soon.

So I wanted to ask, will this cause problems at some point in the future? Arena Tree is fairly small and doesn't seem to have many complex issues that could arise, but I still worry that at some point without a maintainer or anyone in charge of it that it will stop working with upcoming changes to the rust language. Thoughts?

**Comment by kivikakk** [comment]
I've copied the code in already since the package got yanked; if it stops working, it'll simply manifest as comrak itself stopping working, and I'll happily fix it in-tree here.

I think this should be fine?

**Comment by SSJohns** [comment]
Yeah you're right, that works fine.
