### ISSUE TITLE
Benchmark and optimise

### ISSUE THREAD

**Issue by kivikakk** [kivikakk/comrak#4]
Get some benches going to see where to start. #2 is a likely candidate.

**Comment by kivikakk** [comment]
Now at ~3.8x the runtime of `cmark`.

**Comment by kivikakk** [comment]
On the one hand, 4.64x isn't great. On the other hand, it puts comrak between cmark and discount in the [table of benchmarks in `jgm/cmark`](https://github.com/jgm/cmark/blob/12501f1000f592ff67cca98b6733f0bfa3115f9f/benchmarks.md) — so I think it's Good Enough™ for now.

**Comment by Keats** [comment]
FYI, I just made some benchmarks vs pulldown_cmark and comrak is about 2x slower: https://github.com/Keats/markdown-benches-rs

**Comment by kivikakk** [comment]
Thanks for doing that! I'm not entirely surprised, there's a lot of work to be done still. (OTOH, comrak is up to date with the spec, so I guess what you use depends on what you need.)
