### ISSUE TITLE
Generation of Header ID's

### ISSUE THREAD

**Issue by treiff** [kivikakk/comrak#40]
I suspect I may already know the answer to this question, however as I'm not really that familiar with the different markdown specs so thought I would reach out anyway.

Github automatically creates header id's, for example (`id="user-content-about"`)
```
## About

// Renders

<h2>
  <a href="#about" aria-hidden="true" class="anchor" id="user-content-about">
    ...<svg></svg>
  </a>About
</h2>
```

Im guessing github is using  [kramdown#auto-ids](https://kramdown.gettalong.org/converter/html#auto-ids) which is not not supported in comrak, correct? 

This stems from an [issue](https://github.com/rust-lang/crates.io/issues/1037) on crates.io as we're trying to link headers to the appropriate section within the readme.

Thanks for your time!

**Comment by kivikakk** [comment]
GitHub uses [`cmark-gfm`](https://github.com/github/cmark)/[`commonmarker`](https://github.com/gjtorikian/commonmarker); after Markdown is converted to HTML, the HTML is run through a user content stack which e.g. adds user links (like @treiff), issue links, as well as header IDs.

I'll happily add an extension to comrak to do this in a GitHub-compatible matter. I'll let you know via this issue when done, and help integrate it with crates.io.

**Comment by kivikakk** [comment]
Testing a PR at #41 to resolve this.

**Comment by kivikakk** [comment]
Support has now been added. For GitHub compatibility, set the `ext_header_ids` option to `Some("user-content-".to_string())`.
