### ISSUE TITLE
Proposal: Discord-flavored Markdown

### ISSUE THREAD

**Issue by liamwhite** [kivikakk/comrak#420]
Discord-flavored Markdown adds the following optional features, when enabled:

1. "Spoiler" spans, delimited by double pipes `||` (like `Darth Vader is ||Luke's father||`)
    These could emit a configurable tag name (e.g. `span`) with a configurable class name (`spoiler`), or perhaps could be set up with a callback to emit arbitrary markup.
2. Underlined text support, delimited by double underscores `__` (like `__underlined text__`)
   Currently CommonMark prescibes that `__text__` with any number of delimiters is __strong emphasis__, but in Discord-flavored markdown this text is underlined with the `<u>`/`<ins>` tag.
3. Require a space after `>` to begin a blockquote. This allows writing in "greentext style" without adding extra escapes to the beginning `>` character.
4. Disable setext headers. In use, this would be combined with enabling hardbreaks, but currently there is no option to disable setext headers as far as I know.
5. Disable generating links for empty inlines. This prevents links from being generated with no text inside them.

I have been maintaining a downstream fork of this repository with these features implemented for website software I write:
1. [spoilers 1](https://github.com/philomena-dev/comrak/commit/1185a888e38c9644ef04ffc642489dbcdad76d88), [2](https://github.com/philomena-dev/comrak/commit/40f166a5663bed72258ec84b0064495731e44027)
2. [underlines](https://github.com/philomena-dev/comrak/commit/1185a888e38c9644ef04ffc642489dbcdad76d88)
3. [blockquote space requirement](https://github.com/philomena-dev/comrak/commit/0b2b8129434a266734eda746b946d3172cb0ac7f)
4. [setext disable](https://github.com/philomena-dev/comrak/commit/21947798fda8f1148a19f6b6ea171cfdc54f7edf)
5. [empty inlines](https://github.com/philomena-dev/comrak/commit/6a03dabfc80033b24070dc5826c9225686e3a98a)

I would be happy to see any or all of this copied to upstream if these features are considered desirable.

**Comment by kivikakk** [comment]
Hi there! Woah — this is really high quality. Thanks so much for bringing it to my attention!

I'd be happy to upstream all of it. There might(?) be some teething with the hardbreak changes in https://github.com/philomena-dev/comrak/commit/0b2b8129434a266734eda746b946d3172cb0ac7f, but nothing too tricky. Would you like to open a PR?

Also, seeing you have your NIFs already going, I imagine you don't need it, but if you ever want a basis for more AST access from Elixir, I [ported ex-markdown](https://github.com/kivikakk/ex-markdown) to a more recent Comrak not long ago.

**Comment by liamwhite** [comment]
I have posted a PR with these five features extracted into individualized commits for review.

Thanks for the recommendation on ex-markdown, but I would probably have to fork the library to point it to use the fork. There is additional functionality added that is too specific to the software I maintain to be upstreamable (or at least I feel that way), and this would make it not really worth it over just integrating a thin wrapper over the library directly in the application.
