### ISSUE TITLE
Math block with minus at start of a line is parsed as a list

### ISSUE THREAD

**Issue by sheremetyev** [kivikakk/comrak#447]
The following Markdown text

```
$$
- 2
$$
```

is incorrectly parsed as a list: 

```
<p>$$</p>
<ul>
<li>2
$$</li>
</ul>
```

Before removal of math blocks in 003f7776e910199e34050fc3f2408591610e92a1 it was correctly parsed as

```
<p><span data-math-style="display">- 2
</span></p>
```

**Comment by kivikakk** [comment]
@digitalmoksha — would you be able to take a look?

**Comment by sheremetyev** [comment]
fwiw, reverting 003f7776e910199e34050fc3f2408591610e92a1 (tried [here](https://github.com/sheremetyev/comrak/pull/1)) fixes the case when `$$` starts the line but cases when math follows some other text, for example

```
before $$
- 2
$$ after
```

This gets parsed as
```
<p>before $$</p>
<ul>
<li>2</li>
</ul>
<p><span data-math-style="display"></span></p>
```

For reference, Pandoc interprets is as the following (which looks reasonable to me)
```
<p>before <span class="math display">−2</span> after</p>
```

**Comment by sheremetyev** [comment]
I guess this related to the [precedence rule](https://spec.commonmark.org/0.31.2/#precedence) in CommonMark and the question is whether `$$` is block or inline markup.

**Comment by digitalmoksha** [comment]
@sheremetyev thanks for opening this!

`$$` is considered inline content, same way Pandoc handles it. I'll have to see what's going on.

I'm happy to take a look at this, but it will be a couple days before I can dive into it.

**Comment by digitalmoksha** [comment]
> I guess this related to the [precedence rule](https://spec.commonmark.org/0.31.2/#precedence) in CommonMark and the question is whether $$ is block or inline markup.

@sheremetyev sorry it took me a bit to look at this.

You're absolutely right, it comes down to the precedence in CommonMark.  And interestingly, `pandoc` does indeed honor it.

```
pandoc --from commonmark+tex_math_dollars+tex_math_gfm

$$
- x^2
$$
```

yields

```
<p>$$</p>
<ul>
<li>x^2 $$</li>
</ul>
```

When I try it out here on GH, or in https://github.com/jgm/commonmark-hs, I get the same output.

Using 

```
$$
-x^2
$$
```

(remove the space after the `-`) gives the correct rendering.

So I think it's working as intended, though I admit I initially thought it was a bug as well.
