### ISSUE TITLE
Markdown differences

### ISSUE THREAD

**Issue by liamwhite** [kivikakk/comrak#449]
GitHub supports a "difference mode" in its Markdown support. This can be demonstrated e.g. on this repository [here](https://github.com/kivikakk/comrak/commit/a1836e6eab3faa673abd854a08204588b51978a7?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) by selecting the "Rich diff":

|Capture|
|-|
|![image](https://github.com/user-attachments/assets/aba71c45-497b-4f1e-ad5a-837de5cb5600)|

The difference algorithm seems to be at least vaguely syntax-aware, so this isn't necessarily handled on its own by just a Myers diff. Is it possible for comrak to support such a difference mode?

**Comment by gjtorikian** [comment]
I actually worked on this feature when I was at GitHub. It's not a complicated process; I vaguely remember it being a process where the before and after nodes of the HTML trees were walked, with a diff on children that were added or removed. 

I don't know whether comrak should support this natively per se, but one can already walk through the AST on their own. Would a code sample showing that be helpful? How would you ultimately use this feature?

**Comment by liamwhite** [comment]
A code sample would be very helpful, yes. :)

My ultimate plan is to use it in a similar way to how GitHub uses it, for highlighting differences between different versions of forum posts/comments,

**Comment by liamwhite** [comment]
@gjtorikian any update on this?
