### ISSUE TITLE
Problem with Back to Back format ranges

### ISSUE THREAD

**Issue by SSJohns** [kivikakk/comrak#45]
I noticed that if you have a few ranges `**bold*****bold+italic***` back to back the parser puts them out as `<p><strong>bold</strong>***italic***</p>`, basically it is having trouble figuring out where to parse the next range. If you could give me an idea of where this might be happening I would be willing to trying working it out and merge a solution in.

Other examples include:
`**bold*****bold+italic****italic*` outputs
`<p><strong>bold</strong><em><strong>bold+italic</strong>**italic</em></p>`

Ideally the input should be with ranges that are as simple as possible, but in this edge case it seems like things are breaking down.

**Comment by kivikakk** [comment]
Thanks for the report, I'll have a look around. Given we're trying to be an exact copy of the upstream cmark code (which doesn't have this issue), it'll probably be obvious once we spot it.

**Comment by kivikakk** [comment]
We'll want to look around delimiter handling in `src/parser/inlines.rs` (`handle_delim`, `scan_delims`, etc.), comparing with upstream to see where our behaviour differs.

**Comment by kivikakk** [comment]
I've added some debugging and found the root cause; `odd_match` is being calculated differently. With some hasty debugging printfs:

``` console
$ echo '**bold*****bold+italic***' | build/src/cmark-gfm
c: *
c: b
c: *
c: b
c: *
odd_match: false (true, false, 2, 5)
insert emph
opener not found
odd_match: false (false, true, 5, 3)
insert emph
odd_match: false (false, true, 5, 3)
insert emph
<p><strong>bold</strong><em><strong>bold+italic</strong></em></p>
```

vs.

```console
$ echo '**bold*****bold+italic***' | cargo run
    Blocking waiting for file lock on build directory
   Compiling comrak v0.2.5 (file:///Users/kivikakk/kivikakk/comrak)
    Finished dev [unoptimized + debuginfo] target(s) in 5.77 secs
     Running `target/debug/comrak`
c: *
c: b
c: *
c: b
c: *
odd_match: false (true, false, 2, 5)
insert emph
opener not found
odd_match: true (false, true, 3, 3)
opener not found
<p><strong>bold</strong>***bold+italic***</p>
```

(The difference is that `comrak` is reporting 3 for the length of the opener in the second emphasis pass, whereas `cmark-gfm` reports 5. Once fixed this shouldn't be an issue any more.)

**Comment by kivikakk** [comment]
Thanks so much for your report! #46 fixes this.
