### ISSUE TITLE
Fix accuracy of sourcepos for inline elements

### ISSUE THREAD

**Issue by digitalmoksha** [kivikakk/comrak#452]
This issue is for discussing how we might fix the accuracy of `sourcepos` for inline elements.

Simple recreation 

```
A
 B
```

This should generate an AST that looks like this

```
<document sourcepos="1:1-2:2" xmlns="http://commonmark.org/xml/1.0">
  <paragraph sourcepos="1:1-2:2">
    <text sourcepos="1:1-1:1" xml:space="preserve">A</text>
    <softbreak sourcepos="1:2-1:2" />
    <text sourcepos="2:2-2:2" xml:space="preserve">B</text>
  </paragraph>
</document>
```

Instead, the last `text` has `sourcepos="2:1-2:1"`

Related issue [Unexpected sourcepos](https://github.com/kivikakk/comrak/issues/301) and PR [Inline sourcepos fixes](https://github.com/kivikakk/comrak/pull/439) which moved outputting of inline sourcepos into an option, `experimental_inline_sourcepos`

Two other examples captured in tests are https://github.com/kivikakk/comrak/blob/9f4d391abe2857031f993c4cdddf1ebba7cdbc7d/src/tests/core.rs#L580-L603 and https://github.com/kivikakk/comrak/blob/9f4d391abe2857031f993c4cdddf1ebba7cdbc7d/src/tests/core.rs#L532-L555

**Comment by digitalmoksha** [comment]
Including the [comment](https://github.com/kivikakk/comrak/pull/439#issuecomment-2225129960) from @kivikakk in the PR, as a starting point of discussion:

---

How awkward. In all these cases:

```markdown
- A
  B
```

```markdown
- A
B
```

```markdown
- A
   B
```

the inline parser is initialised with the subject `"A\nB"` and a `block_offset` of 2, and doesn't have any distinguishing information. This is a consequence of cmark/Comrak's particular way of collecting block content before handing it off to the inline parser — it normalises things such that the inline parser doesn't need to worry about the minutae of what falls into a block and what doesn't, but we also lose information which we cannot recover.

This will require something of a rearchitecting — sourcepos info needs to be associated and carried through from _much_ earlier in the block processing stage, with the possibility of multiple spans per content block[1] — and I have no real inclination to do such work at present.

In light of all this, for now I'm going to adjust to match upstream (https://github.com/kivikakk/comrak/issues/301#issuecomment-1539424419) and not output inline-level sourcepos in HTML in the same cases as cmark. Block-level sourcepos will be unaffected, as it's not known to have issues.

---

[1] In the examples above, we still need to be passing through the same inline `Subject::input` of `"A\nB"`, but with sourcepos marker collections `[(1:3-1:4),(2:3-2:3)]`, `[(1:3-1:4),(2:1-2:1)]` and `[(1:3-1:4),(2:4-2:4)]` respectively (where `(1:4)` aligns with the `\n` which is turned into a soft break). Right now we only pass a single point `(1:3)` and infer the rest incrementally.

This changes a lot of the bookkeeping on the block parser side, and a complete rework of sourcepos handling on the inline parser side, so I can't even say for sure that I won't hit an even bigger roadblock. Also worth noting in conjunction is [this comment about autolink sourcepos unsoundness](https://github.com/kivikakk/comrak/blob/3bb6d4ceb82e7c875d777899fc8c093d0d3e1fce/src/tests/autolink.rs#L202-L226).

**Comment by digitalmoksha** [comment]
I've started researching this a little, trying to get familiar again with how this works, and play around with a few things.

When I take simple text, such as

```
  A
```

I get 

```
    <text sourcepos="1:3-1:3" xml:space="preserve">A</text>
```

So it doesn't count any leading spaces. So it _seems_ like we would want the same behavior for a following line in the same paragraph.  Meaning

```
  A
   B
```

should yield

```
    <text sourcepos="1:3-1:3" xml:space="preserve">A</text>
    <softbreak sourcepos="1:4-1:4" />
    <text sourcepos="2:4-2:4" xml:space="preserve">A</text>
```

But right now it seems like we're always adding the `block_offset` for the second line, rather than calculating a new start position like we do for the first line. I'm wondering if we can fix that without larger changes 🤔

**Comment by digitalmoksha** [comment]
As an additional researching angle, I've been looking at the output from https://github.com/jgm/commonmark-hs.

For example

```
√ commonmark-hs/commonmark-cli (master= [])
> cabal run exes -- --sourcepos
Up to date
  A
   B

<p data-sourcepos="stdin@1:3-2:1;2:4-3:1"><span data-sourcepos="stdin@1:3-1:4">A</span>
<span data-sourcepos="stdin@2:4-2:5">B</span></p>
```

**Comment by digitalmoksha** [comment]
I know you said this

> the inline parser is initialised with the subject "A\nB" and a block_offset of 2, and doesn't have any distinguishing information. This is a consequence of cmark/Comrak's particular way of collecting block content before handing it off to the inline parser — it normalises things such that the inline parser doesn't need to worry about the minutae of what falls into a block and what doesn't, but we also lose information which we cannot recover.

but it wasn't until I stepped through the code that it clicked into place. Any leading spaces have been stripped off, so we have no idea how many spaces on each line were stripped off.

**Comment by digitalmoksha** [comment]
My initial thought was maybe having a vector of offsets, say `line_offsets`, in the AST for each line that gets added in `add_line`.  It looks like spaces are only trimmed from the beginning of the line.  Then as we process each line in the inline parser, rather than just relying on the `block_offset` and the `column_offset`, we can add in the correct offset for the line.

**Comment by kivikakk** [comment]
If it works, it works! 😸

**Comment by digitalmoksha** [comment]
I spun up https://github.com/kivikakk/comrak/pull/453 to play with some ideas

**Comment by digitalmoksha** [comment]
I think we can close this with #453 merged. Will open another issue if any other problems are found.

There _may_ come a day when we can move inline sourcepos out of experimental status, but it certainly needs more battle testing before that can happen.

@kivikakk would you have time to release a `0.27.0` version? I can certainly do it if needed, but I defer to you.
