### ISSUE TITLE
Bug: code block with empty lines generates invalid HTML 

### ISSUE THREAD

**Issue by soanvig** [kivikakk/comrak#460]
Source:

~~~md
```
const line1 = true;

const line2 = true;
```
~~~

Output HTML:

```html
<pre><code>const line1 = true;
<p>const line2 = true;
</code></pre></p>
```

Expected HTML (which works if there is no empty line in the input markdown):

```html
<pre><code>const line1 = true;
const line2 = true;
</code></pre>
```

Command used: `comrak --syntax-highlighting none --unsafe --gfm`

Comrak version: 0.26.0

---

I think that when there is a code-block paragraphs should not be used at all

**Comment by digitalmoksha** [comment]
Hmm, I'm not able to create that. Using 0.27.0

````
> cargo run -- --syntax-highlighting none --unsafe --gfm
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/comrak --syntax-highlighting none --unsafe --gfm`
```
const line1 = true;

const line2 = true;
```
<pre><code>const line1 = true;

const line2 = true;
</code></pre>
````

I'm also not seeing it at https://gitlab-org.gitlab.io/ruby/gems/gitlab-glfm-markdown/?text=%60%60%60%0Aconst%20line1%20%3D%20true%3B%0A%0Aconst%20line2%20%3D%20true%3B%0A%60%60%60%0A

**Comment by kivikakk** [comment]
Thanks for trying a repro, @digitalmoksha!

@soanvig I cannot reproduce this on 0.26.0, either. Copy-pasting your input, I get the following output:

```html
<pre><code>const line1 = true;

const line2 = true;
</code></pre>
```

Can you clarify how you're producing your result?

**Comment by soanvig** [comment]
I used stdin, maybe it's that?

**Comment by soanvig** [comment]
Sorry, that's my fault. I ran the same file twice through comrak :)
