### ISSUE TITLE
Autolink doesn't handle trailing underscores in links

### ISSUE THREAD

**Issue by liamwhite** [kivikakk/comrak#479]
simple example:
```
$ target/debug/comrak -e autolink <<< "https://x.com/test_"
<p><a href="https://x.com/test">https://x.com/test</a>_</p>
```

**Comment by kivikakk** [comment]
This is intentional and unlikely to change as it corresponds to GitHub's own logic; see: https://x.com/test_

**Comment by liamwhite** [comment]
It might be good to do in Discord flavor since that is the behavior there. I will close this and potentially work on that later.
