### ISSUE TITLE
format_commonmark panics on a single list item

### ISSUE THREAD

**Issue by silverpill** [kivikakk/comrak#485]
Panic occurs when `format_commonmark` input contains a single `NodeValue::Item`:

https://github.com/kivikakk/comrak/blob/v0.29.0/src/cm.rs#L468

It didn't panic before version 0.25.0 (`unwrap` was introduced in #429).

**Comment by kivikakk** [comment]
That's an interesting/unexpected use case! I suppose we can revert to the previous behaviour if the stack is indeed unexpectedly empty:

```rust
let list_number = if let Some(last_stack) = self.ol_stack.last_mut() {
    let ln = *last_stack;
    if entering {
        *last_stack += 1;
    }
    ln
} else {
    match node.data.borrow().value {
        NodeValue::Item(ref ni) => ni.start,
        NodeValue::TaskItem(_) => parent.start,
        _ => unreachable!(),
    }
};
```

What do you think? Please feel free to open a PR; it'd also be great to have a test with your use case in mind so it doesn't regress!

**Comment by silverpill** [comment]
That solution works. I'll submit a PR shortly
