### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nicoburns** [kivikakk/comrak#489]
Hi there! A few changes have landed in Comrak recently (including [mine](https://github.com/kivikakk/comrak/pull/468)!) And I was wondering if it would be possible to get a new release? I'm currently using a git version which is fine for now, but it would be nice to get back on a crates.io release.

**Comment by kivikakk** [comment]
Yes, I'll do so tonight!

**Comment by kivikakk** [comment]
The release is live! ([crates.io](https://crates.io/crates/comrak), [GitHub release](https://github.com/kivikakk/comrak/releases/tag/v0.30.0))
