### ISSUE TITLE
`broken_link_callback` removed support for closures borrowing from their context

### ISSUE THREAD

**Issue by kornelski** [kivikakk/comrak#496]
In https://github.com/kivikakk/comrak/pull/484 the change made the callback require `'static` lifetime, because `Arc` has an implicit `+ 'static` bound. 

This means that closures which borrow from their environment are forbidden now, and must be made to own all of their state. This is especially difficult to use `comrak` in methods that take `&self` and need to call `self.some_lookup_method()` when fixing links.

The same problem still exists when implementing the `BrokenLinkCallback` trait, since `Arc<dyn BrokenLinkCallback>` is always going to require `'static` for every implementation.

I suggest changing it to `Arc<dyn BrokenLinkCallback + 'c>` and restoring the `'c` lifetime on options.

**Comment by kivikakk** [comment]
Hi, thanks for this report! I will loop in @liamwhite here— it seems like we might want to partly revert #484 to permit this.

**Comment by kivikakk** [comment]
Thank you for the report — this was addressed in #499!
