### ISSUE TITLE
Docs aren't available on Docs.rs

### ISSUE THREAD

**Issue by nugend** [kivikakk/comrak#51]
https://docs.rs/comrak

**Comment by kivikakk** [comment]
docs.rs is currently not doing new builds of certain crates :( See onur/docs.rs#23. I'll close this when that gets resolved, but for now `cargo doc` locally will do the trick.

**Comment by kivikakk** [comment]
I've uploaded the docs to GitHub Pages at https://kivikakk.github.io/comrak/ in the meantime!

**Comment by ayosec** [comment]
At this moment, https://docs.rs/comrak/ seems to work properly. I guess that this issue can be closed.
