### ISSUE TITLE
Description List as an extension

### ISSUE THREAD

**Issue by ayosec** [kivikakk/comrak#52]
There is an open [thread about description lists](https://talk.commonmark.org/t/description-list/289) in [talk.commonmark.org](https://talk.commonmark.org/). Since comrak has support for [some extensions](https://github.com/kivikakk/comrak/blob/dfe55ae29482c038c0ba2f4adf925421c6709008/src/parser/mod.rs#L136-L254), I think that it would be nice to add support for definition lists.

## Syntax

There is no official syntax for definition list, but it is implemented in many Markdown processors. One of the comments includes [a list of lins](https://talk.commonmark.org/t/description-list/289/11) to the documentation of some of those processors.

The most common syntax is using colon at the beginning of the definition.

    term1

    : definition1

    term2

    : definition2

This syntax is used in [Pandoc](https://pandoc.org/MANUAL.html#definition-lists), [PHP Markdown](https://michelf.ca/projects/php-markdown/extra/#def-list), [fletcher/MultiMarkdown-4](https://fletcher.github.io/MultiMarkdown-4/definitionlists), [Python Markdown](https://python-markdown.github.io/extensions/definition_lists/), [kramdown](https://kramdown.gettalong.org/quickref.html#definition-lists), etc.

**Comment by kivikakk** [comment]
Awesome! I'd happily accept a PR that implemented this. 😊
