### ISSUE TITLE
Merge lib.rs and main.rs

### ISSUE THREAD

**Issue by brson** [kivikakk/comrak#60]
I honsestly don't know what a best practice is in Rust these days, but havig the two bin/lib split across files makes he imports duplicated and brittle. My prefereence tend to be to have one entry point that can be ethier an exe or a lib. I _feel_ like it would make tracking upstream easier. I'm happy to make the change if you agree.

**Comment by kivikakk** [comment]
I'm super up for this! De-duplicating the imports would be excellent.
