### ISSUE TITLE
HTML boilerplate

### ISSUE THREAD

**Issue by bugabinga** [kivikakk/comrak#69]
Hi!

I am assuming it is intentional that the generated HTML is not a full HTML5 document.
By full, I mean embedded in some kind of template similar to:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>
...
</html>
```

For me this is important, because without `charset="UTF-8"` the browser does not render german umlauts correctly.

Is HTML document generation in scope of `comrak`?
If not, do you happen to have some tips how to script this?

**Comment by kivikakk** [comment]
Hey!

This is indeed intentional; `comrak` is usually used as part of a larger program or library where Markdown content is embedded in a larger document.

How exactly are you using `comrak`? If you're using the library, you can output the necessary header and footer on either side of outputting the converted HTML. If you're using the binary, you could make it part of a larger shell script (or similar) which writes out the necessary HTML.

**Comment by bugabinga** [comment]
> This is indeed intentional; comrak is usually used as part of a larger program or library where Markdown content is embedded in a larger document.
> 
That makes total sense. 
> How exactly are you using comrak? If you're using the library, you can output the necessary header and footer on either side of outputting the converted HTML. If you're using the binary, you could make it part of a larger shell script (or similar) which writes out the necessary HTML.
> 
My intention was to use it like 'pandoc' if you are familiar with it. But it's clear now, that the scopes are very different. 

For now I will cobble together some script, that will pad comrak output with some static HTML and inject a style sheet. 

Could you describe some high level differences of comrak to pulldown-cmark?

**Comment by kivikakk** [comment]
> Could you describe some high level differences of comrak to pulldown-cmark?

They essentially fulfil the same task — CommonMark-compatible Markdown parsing and conversion in Rust.

The main goal of `comrak` is to provide full compatibility with the [GitHub Flavored Markdown](https://github.github.com/gfm/) spec, which is a superset of CommonMark. I believe `pulldown-cmark` is still not at 100% compatibility with the base CommonMark set, and it's not a goal of it to provide GFM-compatibility.

`comrak`'s internal architecture mirrors the reference [`cmark-gfm`](https://github.com/github/cmark) almost exactly. This isn't as efficient as `pulldown-cmark`'s pull parser, but comes with the advantages that: 

1. Anyone familiar with the reference `cmark` code will understand `comrak`'s;
2. When there's a change to the CommonMark spec, which will be accompanied by corresponding changes to `cmark` by the upstream CommonMark team, those changes can be applied almost exactly to `comrak`. This means tracking the spec is super simple.

Those are the key differences. These points notwithstanding, `comrak` and `pulldown-cmark` can more-or-less be exchanged for one another in use with little change.

**Comment by bugabinga** [comment]
Thanks a lot for explaining!
