### ISSUE TITLE
comrak compiler error with Rust 1.26

### ISSUE THREAD

**Issue by ajstrand** [kivikakk/comrak#70]
When using comrak with rust version 1.26 and compiling my project with cargo run on windows 10, I get this error `#[derive(Parser)] not a function`. The error appears to originate in line 8 of your `scanners.rs` file. 

The compiler gives further info saying that the derive attribute should be applied to a function. 

Below is the rust compiler's full explanation of this particular error:

This error indicates that an `#[inline(..)]` attribute was incorrectly placed
on something other than a function or method.

Examples of erroneous code:

```
#[inline(always)]
struct Foo;

#[inline(never)]
impl Foo {
    // ...
}
```

`#[inline]` hints the compiler whether or not to attempt to inline a method or
function. By default, the compiler does a pretty good job of figuring this out
itself, but if you feel the need for annotations, `#[inline(always)]` and
`#[inline(never)]` can override or force the compiler's decision.

If you wish to apply this attribute to all methods in an impl, manually annotate
each method; it is not possible to annotate the entire impl with an `#[inline]`
attribute.

I'm new to rust, but I will see what I can do to resolve this particular error. I will open a PR if I reach a solution. 

P.S. An interesting thing to note is that comrak compiles with cargo run without incident on Rust version 1.25, so I'm not sure if the latest version of Rust broke something or if the Parser library you use broke in a recent update.

**Comment by kivikakk** [comment]
Hey! `pest` had to make some changes for 1.26 compatibility — could you try a `cargo update` and make sure you have the latest `comrak` too?

**Comment by ajstrand** [comment]
Hey @kivikakk it works just fine now. I don't work with Rust much, so I forgot about `cargo update`. But that fixed all my problems. Thanks for being so responsive!

**Comment by kivikakk** [comment]
You're super welcome! :heart: Glad I could help.
