### ISSUE TITLE
`Node` is not visible in the docs

### ISSUE THREAD

**Issue by jDomantas** [kivikakk/comrak#91]
Currently the module structure has some pieces that look somewhat like this (type parameters and fields removed for brevity):

```
mod arena_tree {
    pub struct Node;
}

pub mod nodes {
    pub type AstNode = crate::arena_tree::Node;
}
```

This means that `Node` gets exported publicly through `comrak::nodes::AstNode`, but does not have a documentation page itself (because there is no public item that corresponds to it), so you cannot see what functions it has in the docs. This gets even more confusing as calling functions like `Node::traverse` produces types that are not even mentioned in the docs, not even behind type aliases.

**Comment by kivikakk** [comment]
Thanks for the report! Does #91 fix the issue adequately? (I haven't had my head in amongst this code for a while.)

**Comment by jDomantas** [comment]
Yes, I don't see any missing links in the docs now. Although the link in the module-level docs for `arena_tree` has a space in it, so it might initially seem to the reader to be broken (at least it did for me).

**Comment by kivikakk** [comment]
So it does! I guess that happened due to line wrapping. I'll just unwrap that line.

Thank you so much for checking in with this!
