### ISSUE TITLE
Process broken links

### ISSUE THREAD

**Issue by sunjay** [kivikakk/comrak#95]
In markdown, you can have links separate from their URLs like this:

```md
A link to [github].

[github]: https://github.com/
```

When you process this with comrak, it produces the expected `NodeValue::Link` with the appropriate URL provided at the bottom. This is great!

However, when you try the same thing with a broken link:

```md
A link to [github].
```

Comrak will produce a regular `NodeValue::Text` node with the verbatim text "[github]". This behaviour is correct and expected, but it makes it difficult to implement features that would otherwise replace this link with something else.

For example, the "Rust Intra-rustdoc links" feature would not be able to have ["Implied Shortcut Reference Links"](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#implied-shortcut-reference-links) with the way things are today.

I am working on something that needs the ability to resolve broken links like this instead of having them turn into text. Would it be possible to add something like that to comrak? (The thing I'm working on is not intra-rustdoc links, that was just an example of why this is useful.)

The `pulldown-cmark` crate handles this with a method called [`new_with_broken_link_callback`](https://docs.rs/pulldown-cmark/0.2.0/pulldown_cmark/struct.Parser.html#method.new_with_broken_link_callback) which lets you call a callback whenever the parser encounters any potential links that have a broken reference.

I'm not sure what the best approach for comrak would be, but this may give you some inspiration.

Thanks for such a great library! :smile:

**Comment by kivikakk** [comment]
Howdy! I've had a read-through of the RFC; it should be quite simple to add support for a similar callback. Here's where potential references are dealt with:

https://github.com/kivikakk/comrak/blob/32bafd0b219024877bd046e1012df445611799d9/src/parser/inlines.rs#L942-L982

Alternatively, we could add a new node type for non-matching references which render to HTML/CommonMark/etc. as they are, which you could search for and replace in the AST before rendering. (Or use a custom renderer, either way.)

I'd be very happy to review, give feedback on and accept PRs to implement this feature, whichever way works best. (My own time for new features is very limited, but I do want to make time to get contributors on board.)

**Comment by sunjay** [comment]
@kivikakk It took more effort than I thought, but the PR is up! Thanks for linking to that piece of code. :smile: 

https://github.com/kivikakk/comrak/pull/98

**Comment by sunjay** [comment]
Woot! I got PR #100! Check that out for a new implementation with a broken links callback. :smile: :tada:

**Comment by sunjay** [comment]
This is solved and released. Cheers!
